### ISSUE TITLE
chef_server_url cannot be set through the attributes

### ISSUE THREAD

**Issue by emiliogarcia** [chef-cookbooks/chef-client#211]
No matter what I declare in the attributes I always get 

`chef_server_url "https://localhost:443"`
in the client.rb file. 

My attributes for Chef-Solo

```
{
  "chef-client": {
    "config": {
      "chef_server_url": "https://XXX.YYY.ZZZ.AAA:443",
      "validation_client_name" : "chef-validator"
    }
  },
"run_list": [
    "chef-client::config",
    "chef-client::service"
  ]
}
```

The command I run:
`sudo chef-solo -c solo.rb -j node.json`

The content of client.rb

```
chef_server_url "https://localhost:443"
validation_client_name "chef-validator"
# Using default node name (fqdn)


Ohai::Config[:plugin_path] << "/etc/chef/ohai_plugins"

Dir.glob(File.join("/etc/chef", "client.d", "*.rb")).each do |conf|
  Chef::Config.from_file(conf)
end
```

The OS is Amazon Linux.

Kind regards.

**Comment by donaldguy** [comment]
I am also having this problem; I wonder if the problem is not something to do with a blurring of a line between zero and solo in the move towards chef 12?

It is worth noting that the default setup is defaulting it at `Chef::Config[:chef_server_url]`
https://github.com/opscode-cookbooks/chef-client/blob/79239c09/attributes/default.rb#L29

**Comment by donaldguy** [comment]
I had success just now in raising the precedence from recipe-default to recipe-override perhaps try that - i.e. including it as an attribute in a wrapper cookbook; unfortunately you can not raise the precedence above (or below) normal from a .json

**Comment by lamont-granquist** [comment]
This doesn't really look like a bug.  First trying to set the chef_server_url in a chef-solo run is a really odd use case.  Second all that happens is that attribute is set at a default level in the attributes file.  Any tactic that will have a higher precedence level than that will win.  A wrapper cookbook would work fine.  Roles would work fine.  Even dna.json and normal attributes should also work fine.
