### ISSUE TITLE
chef-client cookbook does not reinstall service if definition has changed

### ISSUE THREAD

**Issue by simonejsing** [chef-cookbooks/chef-client#214]
We want to run the chef-client in a local user account instead of the system account. We can do this by wrapping the chef-client cookbook in our own cookbook and overwrite the attributes for username and password. However, chef does not correctly register that the service needs to be reinstalled if it has already been installed under the systems account.

**Comment by ksubrama** [comment]
This is not specific to username.  The chef-client cookbook does not update a service definition if a previous service of the same name is already present.  This is a limitation in chef-service-manager.  We are tracking bug.

**Comment by ksubrama** [comment]
Related to https://github.com/chef/chef/issues/3948

**Comment by tas50** [comment]
Running as a service has been deprecated. We believe that scheduled tasks provide a much better experience for Windows users and avoid memory leaks related to Ruby on Windows.
