### ISSUE TITLE
chef-client as upstart service does not reload correctly when upstart config has changed

### ISSUE THREAD

**Issue by tgwizard** [chef-cookbooks/chef-client#240]
The service is [notified](https://github.com/opscode-cookbooks/chef-client/blob/master/recipes/upstart_service.rb#L29) to `restart` when the upstart config has changed, which will be equivalent to `service chef-client restart`. This will restart the service but with the old configuration, http://upstart.ubuntu.com/cookbook/#restart.

This makes it tricky to change e.g. the interval config for the chef-client service. To make the service use the new upstart config it should be stopped and then started.

Will something like this work? Should it be `:immediately`?

``` ruby
notifies :stop, 'service[chef-client]', :delayed
notifies :start, 'service[chef-client]', :delayed
```

**Comment by tas50** [comment]
https://github.com/chef/chef/pull/5063 has a fix for this in the chef-client

**Comment by tas50** [comment]
Fixed in the chef-client itself. Update to the latest chef-client to get this fix.
