### ISSUE TITLE
Attribute ruby_bin not available anymore

### ISSUE THREAD

**Issue by Annih** [chef-cookbooks/chef-client#244]
Hello,

The attribute `node['chef_client']['ruby_bin']` has been removed [here](https://github.com/opscode-cookbooks/chef-client/commit/1318def5ab24ea2d6e533ffbd6ace9b024f63d37#diff-25e5d4a4446ae12a0d6f1162b6160375L162) but is still in used in the [task recipe](https://github.com/opscode-cookbooks/chef-client/blob/master/recipes/task.rb#L34).

I'm not sure if this change has been made on purpose but we should mention it in the changelog.

**Comment by juliandunn** [comment]
Yeah, should probably replace that with a helper that does something like

```ruby
require 'rbconfig'
interpreter = File.join(RbConfig::CONFIG["bindir"],
                                  RbConfig::CONFIG["RUBY_INSTALL_NAME"] +
                                  RbConfig::CONFIG["EXEEXT"])
```

**Comment by brugidou** [comment]
+1

**Comment by tas50** [comment]
This appears to be fixed in the latest cookbook release
