### ISSUE TITLE
Chef-Client fails to start (init_service)

### ISSUE THREAD

**Issue by PurrBiscuit** [chef-cookbooks/chef-client#266]
Running chef-client manually to get the chef-client auto-run config set on our nodes and it seems to not be able to start the chef-client service after the initial chef-run completes.  Chef-client completes successfully, everything looks good...

ec2-xx-xx-xx-xx.compute-1.amazonaws.com   \* execute[update npm] action run
ec2-xx-xx-xx-xx.compute-1.amazonaws.com     - execute npm update npm -g
ec2-xx-xx-xx-xx.compute-1.amazonaws.com Recipe: chef-client::init_service
ec2-xx-xx-xx-xx.compute-1.amazonaws.com   \* service[chef-client] action restart
ec2-xx-xx-xx-xx.compute-1.amazonaws.com     - restart service service[chef-client]
ec2-xx-xx-xx-xx.compute-1.amazonaws.com Recipe: nginx::default
ec2-xx-xx-xx-xx.compute-1.amazonaws.com   \* service[nginx] action reload
ec2-xx-xx-xx-xx.compute-1.amazonaws.com     - reload service service[nginx]
ec2-xx-xx-xx-xx.compute-1.amazonaws.com
ec2-xx-xx-xx-xx.compute-1.amazonaws.com Running handlers:
ec2-xx-xx-xx-xx.compute-1.amazonaws.com Running handlers complete
ec2-xx-xx-xx-xx.compute-1.amazonaws.com Chef Client finished, 33/272 resources updated in 162.122408732 seconds

... but when I check the service it doesn't show up as running.

`ops@server:~$ ps aux | grep chef`
`ops      13137  0.0  0.0   8104   916 pts/1    S+   22:06   0:00 grep chef`

...also checking the status of the service returns an ok...

`ops@one-desktop:~$ sudo /etc/init.d/chef-client status`
`* Checking status of chef-client chef-client                                                                                    [OK]`

..checking the logs I see...

`[2015-02-11T22:03:02+00:00] FATAL: Chef is already running pid 10237`

That log is generated at around the same time as the chef-client run that I manually initiated to get chef-client cookbook on my node for the auto-run.  If I manually start the service everything is good after that.

`/etc/init.d/chef-client start`
`ops@server:~$ ps aux | grep chef`
`root     13217  0.0  1.0 134720 42180 ?        Sl   22:17   0:00 /opt/chef/embedded/bin/ruby /usr/bin/chef-client -d -P /var/run/chef/client.pid -c /etc/chef/client.rb -i 300 -s 60`
`root     13248 50.9  2.1 718964 83504 ?        Sl   22:18   0:15 chef-client worker: ppid=13217;start=22:18:19;`

Logs start to generate as well, showing the chef-client is now running on the auto interval we set.  I can do manually chef-runs after I start the service manually and it doesn't affect the daemon.  Auto-runs will continue to run as normal.

Is there anything I can do to make sure the chef-client starts correctly after the first chef run to set it up?  Wasn't sure if this was similar to this issue:  https://github.com/opscode-cookbooks/chef-client/issues/199

**Comment by juliandunn** [comment]
What is the OS you're running under? I can't reproduce this.

**Comment by stephenpurr** [comment]
Ubuntu 12.04.5 LTS

**Comment by alamut** [comment]
met this issue with ubuntu 14.04 and debian 8.
try this workaround, not sure if fits your needs.
```
default['chef_client']['run_path'] = '/run/chef'
```

**Comment by tas50** [comment]
We've done some refactoring to our init script that may have resolved this. If you're still seeing the problem with the 7.0.3 cookbook please open this issue up again.
