### ISSUE TITLE
Dont reload chef-client service when using cron + logrotate

### ISSUE THREAD

**Issue by 8la** [chef-cookbooks/chef-client#284]
Hi, we decide to use cron mode instead of daemon because when you change `client.rb` chef-client tries to restart himself causing to end the actual execution but not starting the service anymore.

In example: 

```
[2015-02-25T09:25:36+00:00] INFO: template[/etc/init.d/chef-client] sending restart action to service[chef-client] (delayed)
[2015-02-25T09:25:36+00:00] INFO: Processing service[chef-client] action restart (chef-client::init_service line 32)
[2015-02-25T09:25:37+00:00] INFO: SIGTERM received, exiting gracefully
[2015-02-25T09:25:44+00:00] FATAL: Chef is already running pid 6227
[2015-02-25T09:25:44+00:00] INFO: service[chef-client] restarted
```

When using the `cron.rb` recipe, we still want to have logrotate feature, but it still try to reload the daemon, it makes no sense. 

It should be a way to not use postrotate when using cron, i.e. set `cron`as the `init_style`, but [the case inside attribute file](https://github.com/opscode-cookbooks/chef-client/blob/master/attributes/default.rb#L173), makes impossible to properly override at time  the `init_style` attribute, to make the case match the right option.

In the mean while we are fixing this on our wrapper cookbook attributes:

``` ruby
default['chef_client']['log_rotation']['postrotate'] = ''
```

But if we have mixed strategies on our servers (i.e. some of them with cron , a coule of them as service...) that is not a good idea.

**Comment by jperville** [comment]
I just got bitten by this gotcha myself: changing `node['chef_client']['interval']` resulted in chef asking to restart the 'chef-client service'; however, the restart of the service (which is the parent process of the current chef-run) had the effect to abort the ongoing chef-run before the service was actually restarted. Then no more periodic chef-runs until the chef-client service is started again manually.

**Comment by jblaine** [comment]
+1

```
/etc/cron.daily/logrotate:

Failed to issue method call: Unit chef-client.service failed to load: No such file or directory.
```
Which begs the point that if the output of the postrotate command is going to be ignored like this:

```
default['chef_client']['log_rotation']['postrotate'] =  case node['chef_client']['init_style']
                                                        when 'systemd'
                                                          'systemctl reload chef-client.service >/dev/null || :'
                                                        when 'upstart'
                                                          'initctl reload chef-client >/dev/null || :'
                                                        else
                                                          '/etc/init.d/chef-client reload >/dev/null || :'
                                                        end
```

Then the commands should squash stderr as well:

```
default['chef_client']['log_rotation']['postrotate'] =  case node['chef_client']['init_style']
                                                        when 'systemd'
                                                          'systemctl reload chef-client.service >/dev/null 2>&1 || :'
                                                        when 'upstart'
                                                          'initctl reload chef-client >/dev/null 2>&1 || :'
                                                        else
                                                          '/etc/init.d/chef-client reload >/dev/null 2>&1 || :'
                                                        end
```

**Comment by eherot** [comment]
Isn't stderr in this case usually sent to email?

**Comment by jblaine** [comment]
With the current code, yes, stderr goes to root email when the service fails to reload (or if the init script is not even present because the machine is not configured to run chef-client as a service).

Our hack/workaround is to undo what this CB now does. We added a file resource to delete /etc/logrotate.d/chef-client :|

**Comment by tgagor** [comment]
There is another issue when running this cookbook on systemd based OS'es (I tested it only on CentOS 7 but it looks like problem may persist on other systemd based systems).
In cron recipe there is template for service: https://github.com/chef-cookbooks/chef-client/blob/master/recipes/cron.rb#L45

```
  template '/etc/init.d/chef-client' do
    source "#{dist_dir}/init.d/chef-client.erb"
    mode 0755
    variables(client_bin: client_bin)
  end```

and this configuration is not proper for systemd based systems. In my opinion this template should be removed or you should use `include_recipe "chef-client::service"` to configure it properly.

As suggested earlier it may not be a bad idea to add init_style cron - that will do cron configuration properly.

**Comment by StephenKing** [comment]
Same issue also here with cron and Debian Jessie. I would say that the `postrotate case` statement should respect `init_style none`. So long, overwriting `default['chef_client']['log_rotation']['postrotate']` helps.

**Comment by rgriffith** [comment]
Just ran into this issue as well. I ran a script with `knife` to check in a set of nodes after adding `chef-client` and a Slack handler and noticed each of the nodes checked in twice. 

Will the suggested workaround of overwriting `postrotate` have any negative impact on log rotation? Are there any plans to address this?

**Comment by dheerajd-msys** [comment]
This issue has been fixed in https://github.com/chef-cookbooks/chef-client/pull/637. 

Closing the issue.

Thanks!!
