### ISSUE TITLE
PID file location inconsistent on ubuntu

### ISSUE THREAD

**Issue by aabes** [chef-cookbooks/chef-client#311]
The default chef-client cookbook seems to create a configuration that allows concurrent execution of a daemon chef, and an interactive chef.

The daemon is controlled by: 
chef-client/templates/default/debian/init.d/chef-client.erb - which sets PID file to: 
PIDFILE=<%= node["chef_client"]["run_path"] %>/client.pid

However, there's no entry generated in /etc/chef/client.rb for either run_path nor lockfile, resulting in the pid file defaulting to /var/chef/cache/chef-client-running.pid

Chef ends up stepping over itself, causing converge failures.

**Comment by runningman84** [comment]
Any news here? This looks like a serious issue...

**Comment by dheerajd-msys** [comment]
@aabes Could you please elaborate steps so as to reproduce the issue?
