### ISSUE TITLE
Add a possibility to set a max execution time for cron job

### ISSUE THREAD

**Issue by pietervogelaar** [chef-cookbooks/chef-client#324]
Yesterday I discovered a Chef server that did not converge for a month, but not failures were shown in the report section of Chef Manage. The chef-client hang on the server and I configured that there may only run 1 chef-client process. So newer ones exited right away as they should.

But I had to kill the running chef-client process. After that I started it manually and it converged again perfectly. To make this process more resilient I would like to change my current cron job:

```
*/30 * * * * root /bin/sleep 526;  /usr/bin/chef-client --run-lock-timeout=0 > /dev/null 2>&1
```

To:

```
*/30 * * * * root /bin/sleep 526;  timeout -s 9 3540 /usr/bin/chef-client --run-lock-timeout=0 > /dev/null 2>&1
```

This way the chef-client run will be killed if it takes 59 minutes (normally it should be finished within a few minutes).

Unfortunately I can only specify daemon_options and no code that comes before the /usr/bin/chef-client command.

**Comment by Nimesh-Msys** [comment]
Commands can easily be overriden by cron resource. Say if we have an entry such that:
```
$ crontab -l
# Chef Name: foo
0 5 * * * root /bin/sleep 526;  /usr/bin/chef-client --run-lock-timeout=0 > /dev/null 2>&1
```

Then core utils(like timeout) or any other options could be added in this manner:
```
cron 'foo' do
  hour '5'
  minute '0'
  command 'root /bin/sleep 526;  timeout -s 9 3540 /usr/bin/chef-client --run-lock-timeout=0 > /dev/null 2>&1'
end
```

Chef-client Output:
```
INFO: cron[foo] updated crontab entry

    - update crontab entry for cron[foo]
```

Updated crontab entry:
```
$crontab -l
# Chef Name: foo
0 5 * * * root /bin/sleep 526;  timeout -s 9 3540 /usr/bin/chef-client --run-lock-timeout=0 > /dev/null 2>&1
```
