### ISSUE TITLE
Setting daemon options breaks when using the cron recipe

### ISSUE THREAD

**Issue by jf647** [chef-cookbooks/chef-client#330]
In the cron recipe, the attribute `node['chef_client']['daemon_options']` is appended to the `client_bin` variable, which is used in the declaration of the cron or cron_d resource to set the command to run in the cronjob.

`client_bin` is also used in the init script (which gets written in the cron recipe, just so that the service can be safely disabled).  So if you mutate `client_bin`, you end up with an init script that looks like this:

```
DAEMON=/usr/bin/chef-client --run-lock-timeout 900
test -x $DAEMON || exit 1
```

This fails with a syntax error because of a lack of quotes around the definition of $DAEMON but would fail on the -x test even if they were there.

The real problem is that this init script should only be written in order to disable it in the cron recipe.  The config recipe sets up a log rotation with a postrotate that calls the init script with a subcommand of `reload`.

The fix I'm proposing is twofold:
- write a syntactically valid dummy starter script, even when daemon_options is set
- prevent the logrotate_app from setting a postrotate attribute when the cron recipe is used

PR to follow shortly

**Comment by jf647** [comment]
PR opened:

https://github.com/opscode-cookbooks/chef-client/pull/331

I wasn't able to override the postrotate attribute,  because

* overriding a lower-level defined value with nil requires Chef 12, and this cookbook needs to continue to work on Chef 11
* even if I guarded it with a node.respond_to?(:rm), the logrotate cookbook will still render this as a postrotate line with no value, because it predicates on the ability to get the instance var as opposed to whether the value of the instance var is defined and/or empty

So this PR ensures that the dummy starter script is syntactically correct.  The logrotate postrotate will still fire '/etc/init.d/chef-client reload' or similar for people using both chef-client::config and chef-client::cron, but since it depends on the existence of a pidfile to actually send the HUP signal, it should be a no-op.

**Comment by manasg** [comment]
Facing the same issue.

**Comment by thebrianlopez** [comment]
+1

**Comment by dheerajd-msys** [comment]
@jf647 We've checked with latest cookbook by setting daemon options in attributes and recipe executes without failure and also it enclosed with double quotes around it.

Please check the execution of the recipe : 
```
Recipe: chef-client::cron
  * directory[/var/run/chef] action create (up to date)
  * directory[/var/chef/cache] action create (up to date)
  * directory[/var/lib/chef] action create (up to date)
  * directory[/var/log/chef] action create (up to date)
  * directory[/etc/chef] action create (up to date)
  * template[/etc/init.d/chef-client] action create
    - update content in file /etc/init.d/chef-client from fee506 to 22328b
    --- /etc/init.d/chef-client	2020-02-19 10:08:34.881244422 +0000
    +++ /etc/init.d/.chef-chef-client20200219-79264-1vgeiqx	2020-02-19 10:46:29.630374210 +0000
    @@ -30,7 +30,7 @@
       mkdir /var/run/chef
     fi
     
    -DAEMON_OPTS="-d -P $PIDFILE -c $CONFIG -i $INTERVAL -s $SPLAY "
    +DAEMON_OPTS="-d -P $PIDFILE -c $CONFIG -i $INTERVAL -s $SPLAY --run-lock-timeout 900"
     
     running_pid() {
       pid=$1
  * template[/etc/default/chef-client] action create (up to date)
  * service[chef-client] action disable (up to date)
  * service[chef-client] action stop (up to date)
  * cron_d[chef-client] action delete
    * file[legacy named cron.d file] action delete (up to date)
    * file[/etc/cron.d/chef-client] action delete (up to date)
     (up to date)
  * cron[chef-client] action create
    - update crontab entry for cron[chef-client]

Running handlers:
Running handlers complete
Chef Infra Client finished, 2/13 resources updated in 07 seconds
```
Closing issue as it's not reproduced. Please let us know if there is anything.
