### ISSUE TITLE
rake spec vs rake travis in travis.yml

### ISSUE THREAD

**Issue by philoserf** [chef-cookbooks/chef-client#336]
I see we have a nice `rake travis` task in the `Rakefile`. Is there a reason we instead call the `rake spec` in the `travis.yml`?

BTW, I never would have noticed had not the build on _master_ been failing.

**Comment by tas50** [comment]
we have the Rake tasks now and Travis is using the commands in chefdk directly since it runs using the chefdk deb in travis.
