### ISSUE TITLE
chef-client support for SLES 11

### ISSUE THREAD

**Issue by rthokala** [chef-cookbooks/chef-client#342]
Hi ,
I'm trying to install chef-client on SLES 11.3 , but for some reason chef-client download page (https://downloads.chef.io/chef-client/) does not show links for SLES. Can some one please point me where to get the files from.

**Comment by juliandunn** [comment]
The Enterprise Linux 6 packages will work on SLES. SLES is not a [Tier 1 platform](https://docs.chef.io/supported_platforms.html).

Also, this issue tracker is only for issues about the Chef Client cookbook, not the Chef client. If you have issues about the Chef client please open them on [that project's issue tracker](https://github.com/chef/chef).
