### ISSUE TITLE
Don't require windows cookbook on linux

### ISSUE THREAD

**Issue by KostyaSha** [chef-cookbooks/chef-client#344]
Windows cookbook adds additional transitive dependencies.
Is it possible to not require windows cookbook on linux platforms?

**Comment by juliandunn** [comment]
This is a limitation in Chef Client and doesn't have anything to do with this cookbook. Chef Client cannot selectively depend or not depend on cookbooks based on the `platform_family`.

As this would be a feature request, please feel free to open a suggestion at our [feedback site](https://feedback.chef.io).
