### ISSUE TITLE
chef-client 12.5.1 breaks LWRP silently

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef-client#345]
This code which works perfectly fine in chef-client 12.4.3 does not work in 12.5.1:
https://gist.github.com/Sauraus/6b699f7726957bb8f577

**Comment by andrefreitas** [comment]
+1, the recipes I wrote last week and deployed are now broken.

**Comment by spuder** [comment]
Could you elaborate how they are broken? Do they show an error?

**Comment by Sauraus** [comment]
Wrong place for the issue, proper location: https://github.com/chef/chef/issues/4124
