### ISSUE TITLE
Impossible to set log_location to STDOUT in client.rb

### ISSUE THREAD

**Issue by e100** [chef-cookbooks/chef-client#348]
When setting log_location to STDOUT client.rb is rendered:
  log_location "STDOUT"

That does not work, it needs rendered without the quotes like:
  log_location STDOUT

**Comment by kareiva** [comment]
Still there. This probably happens due to `.inspect` being used in the client.rb template.

+1

**Comment by coderanger** [comment]
`STDOUT` is an actual Ruby global object representing the stdout stream. `"STDOUT"` is a string which would be used as a filename.

**Comment by kareiva** [comment]
Solution: set `default['chef_client']['log_file'] = nil` to remove log_location from client.rb completely. This defaults to the logs being sent to `STDOUT`

**Comment by kareiva** [comment]
@e100 do you agree to the proposed workaround?

**Comment by ozzyogkush** [comment]
I disagree @kareiva. You can't set attributes to `Nil` in JSON files (environments, roles, run-time JSON etc). Setting it to a falsy value would be better (eg 0, "0", false, "false").

**Comment by ozzyogkush** [comment]
Actually, if you set `node['chef_client']['log_file']` to a non-string (eg `false`), the `config` recipe never sets `node.default['chef_client']['config']['log_location']` and thus should be `Nil`.

**Comment by kareiva** [comment]
Thanks for the clarification. That makes a lot of sense.

On Fri, Jun 3, 2016 at 11:17 PM, Derek Rosenzweig <notifications@github.com>
wrote:

> Actually, if you set node['chef_client']['log_file'] to a non-string (eg
> false), the config recipe never sets
> node.default['chef_client']['config']['log_location'] and thus should be
> Nil.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/chef-cookbooks/chef-client/issues/348#issuecomment-223683443>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADtcTbOnolYgOjcjtRAO4EWIiT-yCKj3ks5qIIvdgaJpZM4GmkzF>
> .
>



-- 
 Simonas K.

**Comment by docwhat** [comment]
Just an update for people searching...

At this time, the chef-client attribute `log_location` also doesn't support:

* `STDOUT`
* `STDERR`
* `Chef::Log::WinEvt.new` (Windows Event Logger)
* `Chef::Log::Syslog.new('chef-client', ::Syslog::LOG_DAEMON)` (Unix Syslog)

**Comment by docwhat** [comment]
I just discovered that in newer versions of chef that `log_location :syslog` and `log_location :win_evt` also work.  So maybe the symbol check code (like `log_level`) should be added for `log_location` as well.

**Comment by docwhat** [comment]
Hah! It is possible to set `log_location 'win_evt'` and it'll work because it changes it to a symbol.  Equally, `chef-client -L win_evt` works too.  Ditto for `chef-client -L syslog`.

**Comment by tas50** [comment]
This was fixed in 6.0
