### ISSUE TITLE
Azure chef-client gets uninstalled

### ISSUE THREAD

**Issue by pmarc01** [chef-cookbooks/chef-client#354]
I have a cluster of windows 2012 servers hosting MongoDB in Azure that got in a bad state and Azure uninstalled the chef-client on many of them. Symptom seems to be the extension will be listed in the Azure portal under the VM, but the service and the c:\opscode directory will be completely gone.

**Comment by tas50** [comment]
This seems like an issue with Azure and not a bug in the chef-client cookbook.  You'll want to follow up with MS support.
