### ISSUE TITLE
SIGHUP kills chef-client when loading handler in client.rb

### ISSUE THREAD

**Issue by rdoorn** [chef-cookbooks/chef-client#365]
Hello,

When we load a library in the /etc/chef/client.rb (using the attributes) we get the following code in the client.rb

```
["sbp_nagios_chefclient_handler/sbp_nagios_chefclient_handler"].each do |lib|
  begin
    require lib
  rescue LoadError
    Chef::Log.warn "Failed to load #{lib}. This should be resolved after a chef run."
  end
end
```

when sending a SIGHUP (kill -1) to the chef-client to reload the configuration, the chef-service client dies

```
[2016-02-15T15:13:33+01:00] FATAL: Configuration error ThreadError: can't be called from trap context
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:3:in `block in from_string'
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:1:in `each'
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:1:in `from_string'
[2016-02-15T15:13:33+01:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

This only happens when loading the library, for the second time due to the sighup.
Tested with a empty library, to exclude code issues:

```
require 'chef/handler'
require 'chef/config'

class SBP
  class Nagios
    class Chefclient
      class Handler < ::Chef::Handler
        def initialize
        end
      end
    end
  end
end
```

Tested on RHEL7 with Chef-client 12.4.3 and 12.7.2

**Comment by tas50** [comment]
@rdoorn It looks like this is actually an issue with the chef-client itself and not the chef-client cookbook. If this is still a problem for you then please file a bug at https://github.com/chef/chef
