### ISSUE TITLE
chef-client exits with Errno::EPIPE: Broken pipe

### ISSUE THREAD

**Issue by kplimack** [chef-cookbooks/chef-client#370]
not sure what's going on here

the run ends with
```
Running handlers:
Running handlers complete
Chef Client failed. 17 resources updated in 02 minutes 20 seconds
```
nothing is displayed on the screen, but `/var/log/chef/client.log` contains
```
[2016-03-13T17:50:57-07:00] ERROR: Running exception handlers
[2016-03-13T17:50:57-07:00] ERROR: Exception handlers complete
[2016-03-13T17:50:57-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-03-13T17:50:57-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-03-13T17:50:57-07:00] ERROR: Broken pipe
[2016-03-13T17:50:57-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
and the stacktrace:
```
# cat /var/chef/cache/chef-stacktrace.out
Generated at 2016-03-13 17:50:57 -0700
Errno::EPIPE: Broken pipe
/opt/chef/embedded/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/buffering.rb:326:in `do_write'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
/opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
/opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:185:in `block in write'
/opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
/opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:184:in `write'
/opt/chef/embedded/lib/ruby/2.1.0/net/http/generic_request.rb:184:in `send_request_with_body'
/opt/chef/embedded/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1412:in `block in transport_request'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1384:in `request'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http/basic_client.rb:65:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:274:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:305:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:303:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:303:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:268:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:143:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/http.rb:118:in `put'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/node.rb:620:in `save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:543:in `save_updated_node'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:705:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:280:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:412:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/chef-client:26:in `<top (required)>'
```

**Comment by tas50** [comment]
@kplimack What version of chef-client and what version of the chef-client cookbook were you running?  Also can you attach the output from chef-client -l debug.

**Comment by kplimack** [comment]
@tas50 oh man, its been so long, and i stripped so much identifying info out of the issue that I'm not even sure where that occurred anymore.  Might be best to close this out and I'll reopen if it resurfaces.

**Comment by tas50** [comment]
Sorry for the late response. I'll close it out and we can dig in if someone else has the same issue

**Comment by kdthanvi** [comment]
happened with me.
`Generated at 2018-03-01 16:42:43 +0900
Errno::EPIPE: Broken pipe
/opt/chefdk/embedded/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'
/opt/chefdk/embedded/lib/ruby/2.1.0/openssl/buffering.rb:326:in `do_write'
/opt/chefdk/embedded/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/protocol.rb:185:in `block in write'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/protocol.rb:184:in `write'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/generic_request.rb:184:in `send_request_with_body'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1412:in `block in transport_request'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1384:in `request'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http/basic_client.rb:65:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:305:in `block in send_http_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:336:in `block in retrying_http_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:334:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:334:in `retrying_http_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:299:in `send_http_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:144:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/http.rb:119:in `put'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/node.rb:601:in `save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:544:in `save_updated_node'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:706:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:283:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:290:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:243:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:450:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:434:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:60:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/bin/chef-client:26:in `<top (required)>'
/opt/chefdk/bin/chef-client:53:in `load'
/opt/chefdk/bin/chef-client:53:in `<main>'`
but running again solved
