### ISSUE TITLE
README for this cookbook needs to be updated to reflect/document the 'chef-client::task' recipe

### ISSUE THREAD

**Issue by joshoohaah** [chef-cookbooks/chef-client#378]
the `readme.md` for this cookbook needs an update to discuss how to properly use/consume the `chef-client::task` recipe.   There is discussion of the attributes this recipe utilizes in the attributes section. But no mention of it in the 'recipes' section, or in the 'services' section.

**Comment by tas50** [comment]
I did some initial documentation of the tasks recipe.  Feel free to open a PR if I missed anything there.

**Comment by joshoohaah** [comment]
looks great. 👍
