### ISSUE TITLE
Add support for new daemonize integer wait flag

### ISSUE THREAD

**Issue by charlesjohnson** [chef-cookbooks/chef-client#379]
In PR https://github.com/chef/chef/pull/4759, we solved for the long-time issue at https://github.com/chef/chef/issues/3305. Adding support for this flag to the chef-client cookbook, with some sane defaults that can help avoid the race condition while not forcing a user to wait for the full splay, would be a great addition to this cookbook.

**Comment by poliva83** [comment]
:+1:
