### ISSUE TITLE
SuSE+systemd service support is not implemented entirely

### ISSUE THREAD

**Issue by conoyes** [chef-cookbooks/chef-client#402]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
4.5.4

### Chef-client version
[Version of chef-client in your environment]
12.10.24

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 1

### Scenario:
[What you are trying to achieve and you can't?]
Create Systemd service for the Chef Client by including the `chef-client::service` recipe in the `run_list`. It fails with `Chef::Exceptions::FileNotFound` because `value_for_platform_family` call doesn't support SuSE.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
Converge the node with these default attributes set:
```
"chef_client": {
   "init_style": "systemd"
}
```

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
Chef client configured to be run according to a systemd service descriptor.

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
The Chef converge fails:
```
  * template[/etc//] action create

    ================================================================================
    Error executing action `create` on resource 'template[/etc//]'
    ================================================================================

    Chef::Exceptions::FileNotFound
    ------------------------------
    Cookbook 'chef-client' (4.5.4) does not contain a file at any of these locations:
      templates/suse-12.1///chef-client.erb
      templates/suse///chef-client.erb
      templates/default///chef-client.erb
      templates///chef-client.erb

    This cookbook _does_ contain: ...
```

**Comment by tas50** [comment]
@conoyes Thanks for pointing this out. I added suse to the systemd recipe and make systemd the default init system for suse platforms. It's released in 4.6.0

**Comment by conoyes** [comment]
@tas50 Thanks. You should be aware though, that SuSE 11 still has SysemV and only from SuSE 12 was systemd intoduced. I'm not sure how pre SuSE 12  systems can use this solution...

**Comment by tas50** [comment]
In general we only support 12+, but someone could set the attribute to init, which *should* just work.

**Comment by conoyes** [comment]
Makes sense. Thank you.
