### ISSUE TITLE
Running Chef Client as a Windows Task Should Support the Windows Event Log

### ISSUE THREAD

**Issue by smurawski** [chef-cookbooks/chef-client#410]
Since the client task recipe sets the log location via the CLI, it does not allow you to use the Windows Event Log logger.

We should support that option here - https://github.com/chef-cookbooks/chef-client/blob/master/recipes/task.rb#L35

**Comment by smurawski** [comment]
Closing in favor of #348

**Comment by oxo42** [comment]
How does #348 resolve this issue?  Do you have an example of a `windows_task` running `OnEvent`?
