### ISSUE TITLE
Add option to change the name of the client log file

### ISSUE THREAD

**Issue by SonyDavid** [chef-cookbooks/chef-client#413]
### Cookbook version

5.0.0
### Chef-client version

12.1.1
### Platform Details

Window 2012R
### Scenario:

Change the Client log file
### Steps to Reproduce:

There no option to change client log file, just location. The log file hard coded on  chef-client/recipes/task.rb line 33
### Expected Result:

Should be able to change the log file

**Comment by tas50** [comment]
This has been done and was just fixed up to be used everywhere in the current release
