### ISSUE TITLE
Chef Automate support should be added

### ISSUE THREAD

**Issue by mattray** [chef-cookbooks/chef-client#423]
The `data_collector.server_url` and `data_collector.token` configuration options should be exposed for management through attributes.

https://docs.chef.io/setup_visibility_chef_automate.html#configure-chef-client-to-send-node-and-converge-data

**Comment by yvovandoorn** [comment]
:+1:

To add to this, it should also handle `knife ssl fetch` if the Automate Server is using a self-signed certificate.

**Comment by tas50** [comment]
@yvovandoorn / @mattray Someone wanna cut a PR for this?

**Comment by jerryaldrichiii** [comment]
As far as @mattray's point goes you can just set:
```
default['chef_client']['config']['data_collector.server_url'] = 'https://my.automate.server/data-collector/v0/'
default['chef_client']['config']['data_collector.token'] = '93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506'
```

Adding explicit support would be nice though.

**Comment by tas50** [comment]
The best way to do this is to add them to the config hash attribute. I'd be open to adding a documentation section to this cookbook that would give examples of how to do that. We should not be adding more attributes to this cookbook though. There's too many as is.

**Comment by jerryaldrichiii** [comment]
Yuuup which is what I meant by my last comment.

I'd keep this issue open for @yvovandoorn's SSL integration (as part of Automate) or move it to a separate issue.

**Comment by tas50** [comment]
@yvovandoorn If you want to open another feature request issue for the ssl fetching stuff that would be helpful to track it
