### ISSUE TITLE
NotImplementedError: user_resource_abstract_base_class in 12.14 and above

### ISSUE THREAD

**Issue by DarrenV79** [chef-cookbooks/chef-client#425]
### Cookbook version

zookeeper 6.0.0
### Chef-client version

> = 12.14
### Platform Details

Ubuntu 14.04 (aws)
### Scenario:

Cookbook cannot converge.  It complains that the 'zookeeper' provider is not implemented.  This is implemented in a default provider.

ERROR: zookeeper[3.4.8](zookeeper::install line 30) had an error: NotImplementedError: user_resource_abstract_base_class[zookeeper](dynamically defined) had an error: NotImplementedError: NotImplementedError
### Steps to Reproduce:

Converge zookeeper
### Expected Result:

It works.  It does on all clients 12.13 and under
### Actual Result:

Gives the error 

ERROR: zookeeper[3.4.8](zookeeper::install line 30) had an error: NotImplementedError: user_resource_abstract_base_class[zookeeper](dynamically defined) had an error: NotImplementedError: NotImplementedError

**Comment by sap2000** [comment]
Ditto here.
For time being did workaround by adding `**--bootstrap-version 12.13.37**`  to `**knife ec2 server create**` command.

**Comment by tas50** [comment]
This repository is for the chef-client cookbook and not the chef-client daemon itself. You'll want to file this issue against the zookeeper cookbook repository.

**Comment by DarrenV79** [comment]
No, this is a Chef problem as it affects other cookbooks also.  Can you please point me to where the functionality change was documented.  Normally Chef warns it will be deprecated in later versions but in this instance it just broke between minor versions.

**Comment by maniaque** [comment]
@DarrenV79 @sap2000 here is a [commit](https://github.com/chef/chef/commit/f769d7eba17b3f5aa9e0561126bd9f6801c1bac2), which is the reason.

The fix seems to be to replace Chef::Resource::User.new(...) with Chef::Resource.resource_for_node(:user, node).new(...)

I personally used `Chef::Resource::User::LinuxUser.new` instead of `Chef::Resource::User.new`

Hope this helps.
