### ISSUE TITLE
Directory templates/default/suse/init.d is missing

### ISSUE THREAD

**Issue by zmahar** [chef-cookbooks/chef-client#426]
### Cookbook version

6.0.0
### Chef-client version

12.13.37
### Platform Details

AWS SLES 12SP1
### Scenario:

Run chef-client::cron recipe.
### Steps to Reproduce:

Run chef-client::cron recipe.
### Expected Result:

Successful run.
### Actual Result:

template[/etc/init.d/chef-client] action create
   ================================================================================
    Error executing action `create` on resource 'template[/etc/init.d/chef-client]'
    ================================================================================

```
Chef::Exceptions::FileNotFound
------------------------------
Cookbook 'chef-client' (6.0.0) does not contain a file at any of these locations:
  templates/suse-12.1/suse/init.d/chef-client.erb
  templates/suse/suse/init.d/chef-client.erb
  templates/default/suse/init.d/chef-client.erb
  templates/suse/init.d/chef-client.erb
```

**Comment by tas50** [comment]
You're right I totally broke this. I've added a SLES 12 box internally so we can test on this and make sure we don't break things in the future. I'll get the file added back.

**Comment by tas50** [comment]
I've added the file back. Check out a new release
