### ISSUE TITLE
OpenSSL 1.0.2j-fips 

### ISSUE THREAD

**Issue by jpae** [chef-cookbooks/chef-client#427]
The latest version of chef-client (12.14.89) has OpenSSL 1.0.2h
```bash
$ /opt/chef/embedded/bin/openssl version
OpenSSL 1.0.2h-fips  3 May 2016
```

Is there a timeline for when 1.0.2j will be bundled in the next chef-client?

**Comment by jschauma** [comment]
This should be marked as a security issue, since the pending OpenSSL update includes fixes for a number of vulnerabilities. I don't see a 'security' label or any other way to mark an issue as such, though.

**Comment by chilicheech** [comment]
I believe this should be in the chef/chef repo as this is a cookbook that installs chef, not the chef client itself. Here's a PR for chef client: https://github.com/chef/chef/pull/5448

**Comment by thommay** [comment]
(As I noted in the Chef PR, we're not affected by either of the vulnerabilities in the release)
