### ISSUE TITLE
systemd service unit file does not notify systemctl daemon-reload

### ISSUE THREAD

**Issue by mathewcrane** [chef-cookbooks/chef-client#428]
### Cookbook version

5.0.0 thru current
### Chef-client version

chef-client 12.6.0
### Platform Details

RHEL 7.x
### Scenario:

Updating /etc/systemd/system/chef-client.service does not trigger a systemctl daemon-reload when updating the file with new directives via chef-client cookbook. Affected recipe: chef-client/recipes/systemd_service.rb
### Steps to Reproduce:

Adjust /etc/systemd/system/chef-client.service manually
Run chef-client cookbook
New service file is put into place
systemctl not made aware of changes until a manual 'systemctl daemon-reload'
### Expected Result:

systemd service file manipulation via chef-client cookbook notifies a 'systemctl daemon-reload' during the execution of that cookbook
### Actual Result:

systemd service file manipulation via chef-client cookbook does not notify systemd via 'systemctl daemon-reload', resulting in a cached/old version of the unit file persisting until manual intervention or another service/process triggers the daemon-reload

Please add something akin to this in chef-client/recipes/systemd_service.rb:

```
template '/etc/systemd/system/chef-client.service' do
  source 'systemd/chef-client.service.erb'
  mode 00644
  variables(client_bin: client_bin, sysconfig_file: "/etc/#{conf_dir}/#{env_file}")
  notifies :restart, 'service[chef-client]', :delayed
  notifies :run, 'execute[daemon-reload]', :immediately
end

<snip>

execute 'daemon-reload' do
  command "systemctl daemon-reload"
  action :nothing
end
```

If possible, backport this to chef-client 5.0.0.

**Comment by tas50** [comment]
We're using the systemd_unit resource now which should be handling all the wonderful systemd unit reloads. Check out the latest release of the cookbook for all of that new functionality
