### ISSUE TITLE
Error performing a kitchen converge with test kitchen. Chef-client cookbook not respecting version pinning constraint

### ISSUE THREAD

**Issue by trekr5** [chef-cookbooks/chef-client#431]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
7.0.0.
### Chef-client version
[Version of chef-client in your environment]
11.18.12

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Using AWS and attempting to run test kitchen on mac OS sierra, version 10.12.1

### Scenario:
[What you are trying to achieve and you can't?]
I'm trying to perform a kitchen converge using test kitchen and receive the following error:-

       Starting Chef Client, version 11.18.12
       Compiling Cookbooks...
       
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/compat_resource/libraries/autoload.rb
       ================================================================================
       
       RuntimeError
       ------------
       This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/compat_resource/libraries/autoload.rb:2:in `<top (required)>'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/compat_resource/libraries/autoload.rb:
       
         1:  unless Gem::Requirement.new(">= 12.0").satisfied_by?(Gem::Version.new(Chef::VERSION))
         2>>   raise "This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade."
         3:  end
         4:  
         5:  # If users are on old verisons of ChefDK which activates an (old) gem via cheffish before this cookbook loads, then
         6:  # we just try to monkeypatch over the top of a monkeypatch.  Its possible that we have checks in this cookbook which
         7:  # will defeat that purpose and fail to monkeypatch on top of monkeypatches -- in which case those checks should be
         8:  # removed -- this cookbook needs to win when it gets into a fight with the old gem versions.
         9:  if Gem.loaded_specs["compat_resource"]
        10:    Chef.log_deprecation "using compat_resource as a gem is deprecated;  please update cheffish and chef-provisioning gems (or use the latest Chef/ChefDK packages) or else manually pin your compat_resource cookbook version to the same version as the gem you are using to remove this warning"
        11:  end
       
       
       Running handlers:
       [2016-11-10T17:17:40+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-11-10T17:17:40+00:00] ERROR: Exception handlers complete
       [2016-11-10T17:17:40+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 8.034320193 seconds
       [2016-11-10T17:17:40+00:00] ERROR: This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.
       [2016-11-10T17:17:40+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

#.kitchen.yml
driver:
     name: ec2
    ...
     require_chef_omnibus: 11.18.12

#Berksfile
source "https://supermarket.chef.io"

metadata

cookbook 'partial_search'
cookbook 'java'
cookbook 'nginx'
cookbook 'chef_handler'
cookbook 'chef-client', '~> 7.0.0'
cookbook 'apt'
cookbook 'filesystem'

#metadata.rb
...

depends 'java'
depends 'nginx'
depends 'partial_search'
depends 'chef_handler'
depends 'chef-client'
depends 'apt'
depends 'filesystem'

#Gemfile
        source 'https://rubygems.org'

    
        gem 'berkshelf', '~> 4.0', '>= 4.0.1'
        gem "test-kitchen"
        gem "kitchen-vagrant"
        gem "kitchen-ec2"
        #gem "dep-selector-libgecode", '~> 1.0'
        gem "chef"

ruby version:
ruby 2.2.5p319

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
I'm expecting to see a successful kitchen converge

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by tas50** [comment]
This cookbook requires Chef 12 so you can't pin to 11 in Test Kitchen. You'll need to upgrade the chef-client daemon in your environment before using the latest releases of this cookbook.
