### ISSUE TITLE
Debug resource always updated at each chef-client run

### ISSUE THREAD

**Issue by lbn-aaio-team** [chef-cookbooks/chef-client#433]
### Cookbook version 7.0.0 - Chef-client version 12.15.19 - windows 2012 R2

Actually when using recipe task on windows plateforms, we meet 2 updated resources even when task is created:

```
Recipe: chef-client::task
  * log[debug client_cmd] action write
  * windows_task[chef-client] action create
Chef Client finished, 2/20 resources updated in 07 seconds
```

this create active nodes in our reporting.

for log message, may cookbook use:
`Chef::Log.debug("Final client_cmd: #{client_cmd}")`

for windows_task, i have no idea^^.

Regards,

**Comment by tas50** [comment]
I removed the debug message in adc4b9d. I'm not sure why that was there.
