### ISSUE TITLE
Clarify readme

### ISSUE THREAD

**Issue by holmesb** [chef-cookbooks/chef-client#435]
### Cookbook version
[7.0.0]

### Scenario:
Struggling to configure client logging via attributes in this cookbook.  Some items in readme seem unfinished: eg

_"node['chef_client']['log_dir'] - Sets directory used in"_
Shouldn't there be an end to this sentence?  If it implies the directory will be used in the next attribute, then that should be spelt out.

_"Chef::Config[:log_location] via command-line option to a location where chef-client should log output. Default "/var/log/chef"."_
This is in attributes section.  If this is not a cookbook attribute (wording suggests is a command-line option rather than attribute) then it shouldn't be in the attribute section.  If it is an attribute, its path should be declared like the others (is it _node['chef_client']['log_location']_?).

_"node['chef_client']['cron']['log_file'] - Location to capture the"_
Another unfinished sentence.

**Comment by tas50** [comment]
Fixed in d52b0ec. Sorry about that
