### ISSUE TITLE
chef-client::task fails on nano server

### ISSUE THREAD

**Issue by Happycoil** [chef-cookbooks/chef-client#439]
### Cookbook version
7.0.0

### Chef-client version
[12.14.60](https://s3-us-west-2.amazonaws.com/nano-chef-client/chef-12.14.60.appx)

### Platform Details
Windows Nano Server 10.0.14393.0

### Scenario:
if chef-client::task (or any other recipe which uses [wmi_property_from_query](https://github.com/chef-cookbooks/chef-client/blob/master/libraries/helpers.rb#L25)) is run on nano server it fails with a WIN32OLERuntimeError.

### Steps to Reproduce:
Include chef-server::task in the run list of a nano server and converge

### Expected Result:
A scheduled task for chef-client is created

### Actual Result:
```
WIN32OLERuntimeError
--------------------
failed to parse display name of moniker `winmgmts://'
    HRESULT error code:0x80004005
      Unspecified error
```

As far as I can tell the line which throws the failure is [this one](https://github.com/chef-cookbooks/chef-client/blob/master/libraries/helpers.rb#L46), but any invocation of wmi_property_from_query will barf.

The relevant Win32_* classes are still queryable with CimCmdlets, for instance:
```powershell
[127.0.0.1]: PS C:\> Get-CimInstance -Query "select * from Win32_UserAccount where sid like 'S-1-5-21-%-500' and LocalAccount=True"

Name             Caption                                  AccountType                              SID                                      Domain
----             -------                                  -----------                              ---                                      ------
Administrator    Nano\Administrator                       512                                      S-1-5-21-850424881-462263701-29929842... Nano
```

**Comment by tas50** [comment]
The scheduled task provider in the windows cookbook does not yet support nano so this cookbook doesn't either. Can you open this issue against https://github.com/chef-cookbooks/windows so we can track it there.
