### ISSUE TITLE
Change to /etc/init.d/chef-client on Debian/Ubuntu introduced in 7.0.2 causes failure of script

### ISSUE THREAD

**Issue by gamer22026** [chef-cookbooks/chef-client#444]
### Cookbook version
7.0.2

### Chef-client version
12.13.37

### Platform Details
Ubuntu 14.04

### Scenario:
Code change introduced by commit https://github.com/chef-cookbooks/chef-client/commit/e271c50b79c3b40c891cca57d73ca8dd7c46a0db causes script to fail

### Steps to Reproduce:
Run /etc/init.d/chef-client

### Expected Result:
/etc/init.d/chef-client script runs without error

### Actual Result:
```/etc/init.d/chef-client: 41: [: /opt/chef/embedded/bin/ruby /usr/bin/chef-client -d -P /var/run/chef/client.pid -c /etc/chef/client.rb -i 1800 -s 300 : unexpected operator```

Line 41 in templates/default/debian/init.d/chef-client.erb
```[ "$cmd" !=~ "$name" ] &&  return 1```
is not valid Bourne shell code

**Comment by tas50** [comment]
7.0.3 has shipped with the fix for this problem.
