### ISSUE TITLE
7.0.2 breaks node['ohai']['plugin_path'] used by older ohai cookbook

### ISSUE THREAD

**Issue by chewi** [chef-cookbooks/chef-client#445]
The nginx cookbook is pegged to ohai `~> 2.0`, which is old but not *that* old and there are updates being proposed. Nevertheless, the default value of `node['ohai']['plugin_path']` was `/etc/chef/ohai_plugins` and now it's `nil`, which breaks installation of plugins. Please keep the old default value or use a different attribute name.

**Comment by tas50** [comment]
The logic of the Ohai 2.0 cookbook is entirely broken. It's model of installing plugins required a full ohai reload on every Chef run as it handled the plugin path incorrectly. Also the legacy nginx cookbook that uses the Ohai 2.0 plugin installs and Ohai 6.0 plugin that will break when compatibility for the legacy plugins is removed. I'd recommend upgrading to our fork of the nginx cookbook which is being maintained and utilizes the updated ohai cookbook with a modern Ohai plugin. https://github.com/chef-cookbooks/chef_nginx

**Comment by Annih** [comment]
@tas50, just to mention that this version also broke the compatibility with all cookbook still using ohai `~> 3.0`. Chef-client has no dependency on the *ohai* cookbook but set one of its attribute to `nil` this is very unpleasant.
