### ISSUE TITLE
log messages

### ISSUE THREAD

**Issue by kmanohar1** [chef-cookbooks/chef-client#449]
I included chef-client::config.rb as first in my runlist and when I run the chef-client first time, the log message does not appear in /var/log/chef/client.log. It appears only when I run the second time.

How do we resolve this issue?

**Comment by rosario-mattera** [comment]
I'm facing the same issue. How could it be resolved?

**Comment by kmanohar1** [comment]
As part of bootstrapping include chef-client::config in the run_list as the first one. This basically fixes the issue.

**Comment by rosario-mattera** [comment]
That's my run-list for a Windows Server 2012 R2 node:
1. chef-client::config
2. chef-client::default

and the first execution has not been logged. Any suggestions?

**Comment by kmanohar1** [comment]
Did you set this as part of bootstrapping? When you run 'knife bootstrap' command?

**Comment by rosario-mattera** [comment]
Yes I did using a defined role, which includes those recipes in that order in the run-list.

**Comment by kmanohar1** [comment]
The default log_level is :auto and so if there are no errors or warnings while running your cookbook , it won't show up.

**Comment by rosario-mattera** [comment]
OK but I've adjusted the log level to info in the default attributes file: however there is no effect on the first run.

`default['chef_client']['config'] = {
  'chef_server_url' => Chef::Config[:chef_server_url],
  'validation_client_name' => Chef::Config[:validation_client_name],
  'node_name' => Chef::Config[:node_name] == node['fqdn'] ? false : Chef::Confi$
  'verify_api_cert' => true,
  'log_level' => :info,
}`

**Comment by cheeseplus** [comment]
The way only way to do this without suffering the issues of the first run is to make this part of the bootstrapping process. I'd suggest looking at https://github.com/juliandunn/chef-bootstrap-templates for examples but essentially one can copy the `chef-full.erb` template and make modifications to what you put in the client.rb. Doing so with Chef isn't really possible in a way in which you can capture that first run.
