### ISSUE TITLE
Chef-client 12.X for Suse Linux server x86_64 architecture

### ISSUE THREAD

**Issue by gopalvd** [chef-cookbooks/chef-client#450]
### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
[Version of chef-client in your environment]
I was looking for the chef-client which is of version 12. above for my Suse Linux server x86_64 architecture. Is that available?
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by tas50** [comment]
This should just work out of the box. Feel free to open a bug report for this if you have a specific problem.
