### ISSUE TITLE
Chef-Client Service Causing Test Kitchen Issues

### ISSUE THREAD

**Issue by kylegoch** [chef-cookbooks/chef-client#457]
### Cookbook version
7.1.0
### Chef-client version
12.17.44
### Platform Details
Ubuntu 16.04
### Scenario:
Chef-client keeps running on test kitchen instances.

When I run Test Kitchen against a role cookbook that also includes `chef-client` cookbook, then I can not re-run `kitchen converge` on that instance because the chef-client service has been installed and is running.

This may be more of a Test Kitchen question, but is it possible to not run the `chef-client` cookbook when im using Test Kitchen. OR is there an attribute I may have missed that I can set in `.kitchen.yml` to disable or restrict the chef-client service?

**Comment by cheeseplus** [comment]
This seems like a case where you don't want to run the cookbook in test-kitchen at all.

**Comment by cheeseplus** [comment]
Closing this because the answer is don't run this inside test-kitchen as the way which tk executes chef is specific to it. There is the possibility to just test the results of the the chef-client cookbook on a first run, just not iteratively with `kitchen converge`.
