### ISSUE TITLE
windows task is created at each chef-client

### ISSUE THREAD

**Issue by lbn-chef-team** [chef-cookbooks/chef-client#460]
Hello,

cookbook chef-client v7.1.0 / windows 2012r2 with chef client 12.17.44 

The windows task is created at each chef-client when using chef-client::task.

<pre>
  * windows_task[chef-client] action create
Folder: \
HostName:                             LBN-NT-DEV1
TaskName:                             \chef-client
Next Run Time:                        1/27/2017 10:00:00 PM
Status:                               Ready
Logon Mode:                           Interactive/Background
Last Run Time:                        N/A
Last Result:                          1
Author:                               Administrator
Task To Run:                          cmd /c " c:\linkbynet\programs\opscode\chef\bin\chef-client -L C:/chef/log/client.
log -c c:\chef/client.rb -s 3600 > NUL 2>&1"
Start In:                             N/A
Comment:                              N/A
Scheduled Task State:                 Enabled
Idle Time:                            Disabled
Power Management:                     Stop On Battery Mode, No Start On Batteries
Run As User:                          SYSTEM
Delete Task If Not Rescheduled:       Disabled
Stop Task If Runs X Hours and X Mins: 72:00:00
Schedule:                             Scheduling data is not available in this format.
Schedule Type:                        One Time Only, Hourly
Start Time:                           10:00:00 PM
Start Date:                           1/27/2017
End Date:                             N/A
Days:                                 N/A
Months:                               N/A
Repeat: Every:                        2 Hour(s), 0 Minute(s)
Repeat: Until: Time:                  None
Repeat: Until: Duration:              Disabled
Repeat: Stop If Still Running:        Disabled
SUCCESS: The scheduled task "chef-client" has successfully been created.
</pre>

I've did some test and it seems that it is the escape characters ^ used at:
https://github.com/chef-cookbooks/chef-client/blob/master/recipes/task.rb
line 43.

when removing this <pre>^> NUL 2^>^&1</pre> the task is not re-created at each chef-client anymore.

Regards,

**Comment by jugatsu** [comment]
Confirmed.
This is because windows_task parses command from schtasks.exe /XML output for idempotence.
https://github.com/chef-cookbooks/windows/blob/master/providers/task.rb#L188
But xml output of ^> transforms to `&gt;` and so & to `&amp;`

**Comment by jugatsu** [comment]
https://github.com/chef-cookbooks/windows/issues/426

**Comment by jugatsu** [comment]
@tas50 In prep for chef-13 it would be great if we fix issue that `chef-client::task` is not idempotent.
As running `chef-client` as a task is recommended way on windows platform.

**Comment by ncerny** [comment]
Hey @jugatsu and @lbn-chef-team - Would you create a pull request with the suggested fix?  Be sure to sign the DCO, and sign-off the commits!

**Comment by jugatsu** [comment]
@ncerny already done https://github.com/chef-cookbooks/chef-client/pull/466

**Comment by ncerny** [comment]
Awesome!  Thanks, I didn't see that!

**Comment by jugatsu** [comment]
@lbn-chef-team can be closed. fixed https://github.com/chef-cookbooks/chef-client/pull/466
