### ISSUE TITLE
windows - add client_key entry to client.rb to cover edge case

### ISSUE THREAD

**Issue by tehsuk** [chef-cookbooks/chef-client#461]
### Cookbook version
NA

### Chef-client version
12.18.31

### Platform Details
Windows Server 2016

### Scenario:
If the directory you are running knife boostrap from is on a volume other than C:, and you add your local node to a chef server, the first run of chef-client looks in the wrong location for client.pem

### Steps to Reproduce:
Install ChefDK to d:\ChefDK
Create repo in D:\chefdk\repo
deploy your knife.rb to d:\chefdk\repo\.chef\knife.rb & pem file to same directory
push-location d:\chefdk\repo
knife bootstrap windows winrm $env:computername

### Expected Result:
node  you run from gets added to chef server

### Actual Result:
chef-client when running c:\chef\first-boot.json looks in D:\chef\client.pem, but the bootstrap steps that happen prior to that save it in c:\chef\client.pem

servername C:\Users\user>chef-client -c c:/chef/client.rb -j c:/chef/first-boot.json
servername [2017-02-20T11:15:01-05:00] INFO: *** Chef 12.18.31 ***
servername [2017-02-20T11:15:01-05:00] INFO: Platform: i386-mingw32
servername [2017-02-20T11:15:01-05:00] INFO: Chef-client pid: 3652
servername [2017-02-20T11:15:07-05:00] INFO: Client key D:\chef\client.pem is not present - registering
servername
servername ================================================================================
servername Chef encountered an error attempting to create the client "w16rgrm-tool01"
servername ================================================================================
servername
servername Platform:
servername ---------
servername i386-mingw32
servername
servername [2017-02-20T11:15:07-05:00] ERROR: Running exception handlers
servername [2017-02-20T11:15:07-05:00] ERROR: Exception handlers complete
servername [2017-02-20T11:15:07-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
servername [2017-02-20T11:15:07-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
servername [2017-02-20T11:15:07-05:00] FATAL: Chef::Exceptions::CannotWritePrivateKey: I can't write your private key to D:/chef/client.pem - check permissions?
ERROR: Failed to execute command on servername return code 1
ERROR: Bootstrap command returned 1

### Workaround:
Editing c:\chef\client.rb after it is generated, and adding the following line:

client_key        "c:/chef/client.pem"

While googling this issue i found references where this entry is added during the bootstrap operation, but it didn't end up on mine.

**Comment by smurawski** [comment]
I don't believe ChefDK is supported on drives other than `C:\`.  In order to install gems that have native compilation, ChefDK will look for the Ruby DevKit install at `C:\opscode\chefdk\embedded`   https://github.com/chef/chef-dk/blob/9199ddcb6d1504749cbe689347d6b895b0bd889b/omnibus/files/rubygems-customization/windows/operating_system.rb#L66
