### ISSUE TITLE
Chef-Client Compatibility With SUSE Linux Enterprise Server 11 x86 Architecture

### ISSUE THREAD

**Issue by scott-wood-vgh** [chef-cookbooks/chef-client#471]
### Chef-client version
[Version of chef-client in your environment]
12.19.36

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
SUSE Linux Enterprise Server 11 (x86_64)

### Scenario:
[What you are trying to achieve and you can't?]

Trying to install Chef-Client on SUSE Linux Enterprise Server 11 (x86_64) but the RPM file provided here (https://downloads.chef.io/chef#sles) fails with the following error:

warning: chef-12.19.36-1.sles11.s390x.rpm: Header V4 DSA signature: NOKEY, key ID 83ef826a
Preparing packages for installation...
	package chef-12.19.36-1.sles11.s390x is intended for a s390x architecture

Is there a way I can install the Chef Client on the x86 architecture I have?

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

Try to install Chef-Client from the RPM file here: https://downloads.chef.io/chef#sles for SUSE Linux Server 11.

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
Install Chef Client and configure it for my Chef Server (on Ubuntu 16.04 if it matters)
### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
Unable to install Chef-Client due to error referenced above.

**Comment by cheeseplus** [comment]
We don't offer a specific build for x86_64 SLES 11 though the RHEL6 build should work fine. Alternatively you can install chef the old fashioned way via gems as we do "support" SLES 11 in terms of code even though we only make one official build. The reason we have s390 as an official package is that this is sponsored/consumed by a customer.

As this isn't an issue on the cookbook itself I'm closing this but happy to answer questions in the Chef Community Slack http://community-slack.chef.io/

**Comment by cheeseplus** [comment]
For posterity we now do offer SLES 11 builds as officially supported and their own packages.
