### ISSUE TITLE
chef-client 13 and amazon linux platform_family change

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/chef-client#475]
### Cookbook version
8.0.0

### Chef-client version
13.0.118

### Platform Details
Chef-Client 13 and Amazon Linux running on AWS cloud

### Scenario:
Chef-client is configuring service

### Steps to Reproduce:
create an amazon linux instance with chef-client 13 and chef-client cookbook in the runlist.

### Expected Result:
chef-client service to be created and started

### Actual Result:
most of the code is skipped due to chef-client 13 now being it's own platform_family and case statements not accounting for it.

**Comment by tas50** [comment]
This was released in 8.0.1
