### ISSUE TITLE
windows task fail on chef 13 

### ISSUE THREAD

**Issue by lbn-chef-team** [chef-cookbooks/chef-client#476]
### Cookbook version
chef-client (8.0.1)

### Chef-client version
chef_version=13.0.118 (was working on chef 12.19.36

### Platform Details
platform=windows
platform_version=6.3.9600
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

### Steps to Reproduce:
recipe in a wrapper cookbook:
include_recipe 'chef-client::task'

with attributes:
default['chef_client']['interval'] = 7200
default['chef_client']['splay'] = 3600
default['chef_client']['task']['frequency'] = 'hourly'
default['chef_client']['task']['frequency_modifier'] = node['chef_client']['interval'].to_i / 3600

### Expected Result:
windows task to be created

### Actual Result:
Recipe: chef-client::task
  * windows_service[chef-client] action configure_startup[2017-04-20T10:21:07+02:00] INFO: Processing windows_service[ch
ef-client] action configure_startup (chef-client::task line 21)
 (skipped due to only_if)
  * chef_client_scheduled_task[Chef Client] action add[2017-04-20T10:21:07+02:00] INFO: Processing chef_client_scheduled
_task[Chef Client] action add (chef-client::task line 27)

Error executing action `add` on resource 'chef_client_scheduled_task[Chef Client]'

    RuntimeError
    ------------
    can't modify frozen String

    Resource Declaration:
    ---------------------
    In c:/chef/cache/cookbooks/chef-client/recipes/task.rb

     27: chef_client_scheduled_task 'Chef Client' do
     28:   user node['chef_client']['task']['user']
     29:   password node['chef_client']['task']['password']
     30:   frequency node['chef_client']['task']['frequency']
     31:   frequency_modifier node['chef_client']['task']['frequency_modifier']
     32:   start_time node['chef_client']['task']['start_time']
     33:   splay node['chef_client']['splay']
     34:   config_directory node['chef_client']['conf_dir']
     35:   log_directory node['chef_client']['log_dir']
     36:   chef_binary_path node['chef_client']['bin']
     37:   daemon_options node['chef_client']['daemon_options']
     38: end

    Compiled Resource:
    ------------------
    Declared in c:/chef/cache/cookbooks/chef-client/recipes/task.rb:27:in `from_file'

    chef_client_scheduled_task("Chef Client") do
      action [:add]
      default_guard_interpreter :default
      declared_type :chef_client_scheduled_task
      cookbook_name "chef-client"
      recipe_name "task"
      user "SYSTEM"
      password nil
      frequency "hourly"
      frequency_modifier 2
      start_time nil
      splay 3600
      config_directory "c:\\chef"
      log_directory "C:/chef/log"
      chef_binary_path "c:\\linkbynet\\programs\\opscode\\chef\\bin\\chef-client"
      daemon_options []
    end

    System Info:
    ------------
    chef_version=13.0.118
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
    program_name=C:/LinkByNet/Programs/opscode/chef/bin/chef-client
    executable=C:/LinkByNet/Programs/opscode/chef/bin/chef-client

[2017-04-20T10:21:07+02:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-04-20T10:21:07+02:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-20T10:21:07+02:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 10 seconds
[2017-04-20T10:21:07+02:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2017-04-20T10:21:07+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-20T10:21:07+02:00] FATAL: RuntimeError: chef_client_scheduled_task[Chef Client] (chef-client::task line 27) had
 an error: RuntimeError: can't modify frozen String

### chef-stacktrace.out

Generated at 2017-04-20 10:50:19 +0200
RuntimeError: chef_client_scheduled_task[Chef Client] (chef-client::task line 27) had an error: RuntimeError: can't modify frozen String
c:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb:38:in `block in class_from_file'
(eval):2:in `block in action_add'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/provider.rb:211:in `instance_eval'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_add'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/LinkByNet/Programs/opscode/chef/bin/chef-client:69:in `load'
C:/LinkByNet/Programs/opscode/chef/bin/chef-client:69:in `<main>'

>>>> Caused by RuntimeError: can't modify frozen String
c:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb:38:in `block in class_from_file'
(eval):2:in `block in action_add'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/provider.rb:211:in `instance_eval'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_add'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/LinkByNet/Programs/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/LinkByNet/Programs/opscode/chef/bin/chef-client:69:in `load'
C:/LinkByNet/Programs/opscode/chef/bin/chef-client:69:in `<main>'

**Comment by jeremysmitherman** [comment]
We reverted back to 7.1.0 and that solved our issue with chef version 13.  7.2.0 probably works as well but we went back to an absolutely known good working version.

**Comment by andrewelizondo** [comment]
I ran into the same problem, same scenario 👍
