### ISSUE TITLE
Add default cron environment to account for Ohai changes

### ISSUE THREAD

**Issue by StuporHero** [chef-cookbooks/chef-client#478]
### Cookbook version
8.0.1

### Chef-client version
13.0.118

### Platform Details
oracle-6.9

### Scenario:
Configuring chef-client to run as a cron job causes ohai not to find the `ip` command. It seems that ohai's mechanism for resolving the location of the `ip` command was changed from an explicit path search to using the PATH environment variable between the last version I used (8.20.0) and the current version (13.0.1). On oracle-6.9, the PATH variable for cron jobs is `/usr/bin:/bin` and the `ip` command is located at `/sbin/ip`. I was able to make it work by setting `node['chef-client']['cron']['environment_variables']` to `PATH=/usr/bin:/bin:/sbin`. Since this scenario specifically affects cron jobs, I decided this would be the most appropriate place to file this since this cookbook could include a default environment, or perhaps more ideally a specific `node['chef-client']['cron']['path']` setting, to obviate the need to manually set the environment apart from truly exceptional configurations.

### Steps to Reproduce:
Run the `chef-client::chef-cron` recipe with any schedule (* * * * is most convenient for testing).

### Expected Result:
`/var/log/chef/client.log` should indicate a successful chef-client run.

### Actual Result:
`/var/log/chef/client.log` contains `WARN: Plugin Network: unable to detect ipaddress`

**Comment by tas50** [comment]
This is actually an ohai bug that we're working on for the 13.1 release. https://github.com/chef/ohai/issues/990
