### ISSUE TITLE
windows - client.rb not updated

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef-cookbooks/chef-client#479]
### Cookbook version
`8.0.1`

### Chef-client version
```
C:\chef>chef-client --version
Chef: 12.19.36
```

### Platform Details
`Windows 2012 R2 - [Version 6.3.9600]`

### Scenario:
I noticed when using the cookbook that my `client.rb` wasn't being updated, walking through the code I can't see a `template` resource being defined if my platform is windows?

**I would like to add that it worked flawlessly in recreating a working scheduled task, thanks very much :+1:** 

### Steps to Reproduce:
On windows 
chef-client::default > chef-client::task
that then ran the following
* disable `windows_service` "chef-client"
* create `chef_client_scheduled_task`

### Expected Result:
My `client.rb`  should be updated with my custom log location.

### Actual Result:
client.rb is not updated.

```
Starting Chef Client, version 12.19.36
resolving cookbooks for run list: ["chef-client"]
Synchronizing Cookbooks:
  - chef-client (8.0.1)
  - cron (4.1.1)
  - compat_resource (12.16.2)
  - logrotate (2.1.0)
  - windows (2.1.1)
  - ohai (4.2.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: chef-client::task
  * windows_service[chef-client] action configure_startup (skipped due to only_if)
  * chef_client_scheduled_task[Chef Client] action add
    * directory[C:/chef/run] action create (up to date)
    * directory[C:/chef/cache] action create (up to date)
    * directory[C:/chef/backup] action create (up to date)
    * directory[C:/chef/log] action create (up to date)
    * directory[C:/chef] action create (up to date)
    * windows_task[chef-client] action create (up to date)
     (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 0/8 resources updated in 06 seconds
```

**Comment by shoekstra** [comment]
This can be solved by including the `chef-client::config` recipe before `chef-client::default`.

**Comment by tas50** [comment]
As @shoekstra mentioned the config recipe is responsible for creating the client.rb file. Without this recipe being added to the run_list we don't touch the config. This is actually be design so users can choose if they want to manage the service or manage everything.
