### ISSUE TITLE
Windows task doesn't update when interval is changed

### ISSUE THREAD

**Issue by pjjohnstone** [chef-cookbooks/chef-client#480]
### Cookbook version
8.0.1

### Chef-client version
12.19.36

### Platform Details
Windows Server 2012 R2

### Scenario:
Changing the 'interval' attribute in a cookbook to increase or decrease frequency of chef runs.

### Steps to Reproduce:
Run chef-client cookbook on a windows node with one value for "interval" e.g 1800, or 30 minutes.
Change the interval attribute for that node, in my case I am changing the default attribute on a wrapper cookbook.
Run chef-client on the node again

### Expected Result:
The interval of the scheduled task should change

### Actual Result:
The interval doesn't update, the log shows the following:
`[2017-04-25T15:04:22+01:00] INFO: windows_task[chef-client] task already exists - nothing to do
 (up to date)
     (up to date)`

**Comment by pjjohnstone** [comment]
Having looked at the code it seems like this might be caused by this issue: https://github.com/chef-cookbooks/windows/issues/366

**Comment by cheeseplus** [comment]
Closing this on the cookbook - this is a core chef issue that is noted in https://github.com/chef-cookbooks/windows/issues/366

**Comment by rosario-mattera** [comment]
Hi,
How can I fix this on a deployed host using chef-client 12.18.31?
