### ISSUE TITLE
Chef-Client fails on SLES 11 x86_64

### ISSUE THREAD

**Issue by rosario-mattera** [chef-cookbooks/chef-client#481]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
7.1.0
### Chef-client version
[Version of chef-client in your environment]
13.0.123
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
SLES 11 x86_64
### Scenario:
[What you are trying to achieve and you can't?]
The chef-client executions next to the first one fail.
### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
Bootstrap the SLES node and let it execute the chef-client each 30 minutes as default configuration
### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
The chef-client executes successfully.
### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
Chef-client fails due to the following error:

> #<Errno::EISDIR: Is a directory @ io_fread - /> had an error:
> Is a directory @ io_fread - /

The stacktrace output is
```
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/mixin/from_file.rb:30:in `read'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/run_context.rb:363:in `load_recipe_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/policy_builder/expand_node_object.rb:100:in `block in setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/policy_builder/expand_node_object.rb:99:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/policy_builder/expand_node_object.rb:99:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```

**Comment by iennae** [comment]
This looks like it might be an issue with chef-client and not with this cookbook itself. https://github.com/chef/chef#reporting-issues. 
Based on your description it sounds like you are able to converge the node, but it fails on following runs? If this is a chef-client issue can you open an issue on the chef/chef project? Thanks.

**Comment by rosario-mattera** [comment]
Hi,
I've raised the same issue on the chef mailing-list at the following thread

[(https://discourse.chef.io/t/how-to-install-chef-client-on-sles-11-x86-64/10801/6)]

**Comment by iennae** [comment]
Thanks for the link to discourse which provides more details. Right now opensuse uses systemd for init which is why in [attributes](https://github.com/chef-cookbooks/chef-client/blob/master/attributes/default.rb#L109) it's configured to use systemd for init.d. We need to reevalute how this is done to make sure we don't break opensuse, identify a activation mechanism for us to test against SUSE Enterprise Linux, and then update this cookbook.

**Comment by tas50** [comment]
8.0.2 should fix this based on the discourse conversation. Give that a try and feel free to open this back up if you're still having issues.

**Comment by raghuteja9** [comment]
Hi @tas50 I am facing the same issue on our SUSE nodes. I am using the latest version of the chef client cookbook.

**Comment by raghuteja9** [comment]
Hi @cheeseplus - Thanks for re-opening this issue.

**Comment by kmf** [comment]
Also effected by this issue.

**Comment by VIshalgoel011** [comment]
[root@Chef-work .chef]# knife bootstrap 192.168.117.135 --sudo -x admin -p root123 -N "test-node"
Connecting to 192.168.117.135
ERROR: Errno::EISDIR: Is a directory @ io_fread - /root/.chef

I am getting above error can asist me

**Comment by raghuteja9** [comment]
Hi All,
I have overcome the above issue by creating a wrapper cookbook around chef client cookbook and have the below code in the default recipe of the wrapper cookbook.

if node['platform'] == 'suse' && node['platform_version'].to_i == 11
node.normal['chef_client']['init_style'] = 'none'
node.normal['chef_client']['cron']['minute'] = '*/10'
node.normal['chef_client']['cron']['hour'] = '*'
include_recipe 'chef-client::cron'
end
include_recipe 'chef-client::default'

So for suse 11 we need to include the cron recipe which would create a cron job and you can update the above attributes like i have it set to run the chef client every 10 mins. I have also restarted my test server to see if it was able to run the chef-client and it was working fine. 
@tas50 - Let me know if what i have done is a correct way to solve this issue?
Thanks in Advance.

**Comment by kmf** [comment]
+1 affected by this bug

**Comment by kmf** [comment]
What is the status of this bug?

**Comment by kmf** [comment]
@raghuteja9 could you perhaps reshare your code snippet ... think the markdown formatting changed it a bit.

**Comment by dheerajd-msys** [comment]
Hi @raghuteja9,

Could you please give it a try with latest chef-client cookbook?

Thanks!!

**Comment by dheerajd-msys** [comment]
@raghuteja9 SLES 11 is now EOL so we won't be resolving this issue. You'll want to upgrade to a currently supported SLES release
