### ISSUE TITLE
Bug in Client.rb.erb when adding ['chef_client']['config] items

### ISSUE THREAD

**Issue by unscrum** [chef-cookbooks/chef-client#486]
### Cookbook version
7.2.1

### Chef-client version
12.16.42

### Platform Details
Windows 2012R2

### Scenario:
Attempting to set the attribute ['chef_client']['config']['log_location'] to use windows event log.  When the new client.rb gets updated it fails to put a new line after the log location line and the following line which just happens to be the PEM file is now on the same line as log_location and chef runs fail.

In looking at the client.rb.erb line 20 it is
<%= option %> <%= @chef_config[option] -%>
but should be
<%= option %> <%= @chef_config[option] %>
so that the new line is not removed.

### Steps to Reproduce:
in a cookbook that calls the chef_client::config recipe add in an override attribute for ['chef_client']['config']['log_location'].  

### Expected Result:
the log_location set in the attribute should be on its own line

### Actual Result:
the log_location and what should be the ssl_ca_file  end up on the same line

**Comment by iennae** [comment]
Can you share what you have  ['chef_client']['config']['log_location'] set to? The -%> and %> aren't going to be an issue here unless erubis templating is different on windows/non-windows platforms.

**Comment by unscrum** [comment]
Is set to :win_evt. The -%> should only be used for "if" or "each" or "case" like blocks. Not for writing out lines with "<%=".

**Comment by iennae** [comment]
Are you overriding "log_file"?

**Comment by iennae** [comment]
I'm not able to duplicate the error that you are running into:

Using test kitchen I have the following configured

  - recipe[chef-client::config]
  attributes:
    chef_client:
      config:
        log_location: :win_evt

My first chef-client run, I gave chef-client the wrong options and it got logged
![screen shot 2017-05-15 at 9 25 15 pm](https://cloud.githubusercontent.com/assets/1592404/26089779/1ec3ab40-39b5-11e7-9b5b-64c07ca8e01a.png)

The second chef-client run it ran successfully: 
![screen shot 2017-05-15 at 9 25 29 pm](https://cloud.githubusercontent.com/assets/1592404/26089780/20221fda-39b5-11e7-9af7-7be488d5661b.png)

**Comment by iennae** [comment]
And the converge information:
<details>

>            - create new file C:/chef/client.rb
>            - update content in file C:/chef/client.rb from none to 397dbf
>            --- C:/chef/client.rb	2017-05-15 21:20:22.000000000 -0700
>            +++ C:/chef/chef-client20170515-3044-1s3q9we.rb	2017-05-15 21:20:22.000000000 -0700
>            @@ -1 +1,18 @@
>            +chef_server_url "chefzero://localhost:8889"
>            +client_fork true
>            +log_location ":win_evt"
>            +validation_client_name "chef-validator"
>            +verify_api_cert true
>            +node_name "config-windows-2012r2"
>            +
>            +
>            +ohai.plugin_path << "/tmp/kitchen/ohai/plugins"
>            +ohai.disabled_plugins = ["Mdadm"]
>            +
>            +# Do not crash if a handler is missing / not installed yet
>            +begin
>            +rescue NameError => e
>            +  Chef::Log.error e
>            +end
>            +
>            - change dacl
>            - change owner
>            - change group
>          * ruby_block[reload_client_config] action create
>            - execute the ruby block reload_client_config
>          * directory[C:/chef/client.d] action create
>            - create new directory C:/chef/client.d
>            - change dacl
>            - change owner
>            - change group
>          * ruby_block[reload_client_config] action nothing (skipped due to action :nothing)
> 

</details>

**Comment by iennae** [comment]
I should mention that -%> and %> really don't matter at this point based on the version of erubis we use as far as I know.

**Comment by iennae** [comment]
I double checked and apparently it does matter. I still haven't replicated the issue that you are reporting though with that particular line so before I make changes I want to make sure I see the problem.

Thanks for your help with this!

**Comment by iennae** [comment]
last question for this evening, are you are setting this attribute to :win_evt or ":win_evt"?

**Comment by unscrum** [comment]
I guess it doesn't really matter what I use for the log value.  The line below it is being appended to the log value because there is no new line between.  If you are not seeing the behavior ensure that you have more options set below the log line.  If the log line is the last line in the file client.rb then there is no issue. Only if there are more options specified afterwards.  The the log line is in error and what should be the next line is ignored at runtime since it's appended to the log value.

**Comment by iennae** [comment]
It matters what you use for the log value because :win_evt is passing to the template the value of that symbol, and ":win_evt" is a string with the contents :win_evt which is what needs to be set. 

I can replicate your issue if the attribute is :win_evt. You need to pass a string in.

**Comment by unscrum** [comment]
The cookbook adds quotes but not a new line you're suggesting?   The doc days set it to :win_evt.

**Comment by iennae** [comment]
I'm saying that if it's a string, then you don't get the -%> behavior. I can fix the docs, but it'd be helpful to hear back from you if modifying it to be a string fixes your problem.

**Comment by unscrum** [comment]
I can try that again. But I believe I tried using an actual folder location as well and had the same issue.

**Comment by pwalz** [comment]
I believe this was fixed by #561

**Comment by dheerajd-msys** [comment]
@unscrum Please confirm if #561 fixes your issue?

Thanks!!

**Comment by dheerajd-msys** [comment]
@unscrum Please check ^
