### ISSUE TITLE
Unable to satisfy constraints on package chef-client (8.0.2)

### ISSUE THREAD

**Issue by jpSimkins** [chef-cookbooks/chef-client#487]
### Cookbook version
8.0.2

### Chef-client version
12.20.3

### Platform Details
CentOS Linux release 7.3.1611 (Core)  - AWS EC2 Instance

### Scenario:
Having issues already reported [here](https://github.com/chef-cookbooks/chef-client/issues/464#issuecomment-299618192) with version 8.0.1. Updating to see if latest version would solve issue.

### Steps to Reproduce:
Increment version in cookbook metadata from 8.0.1 to 8.0.2. Run `berks install`

### Expected Result:
Expected to see the typical response when running `berks install`

### Actual Result:
```
# berks install
Resolving cookbook dependencies...
Fetching 'oly-client' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Unable to satisfy constraints on package chef-client due to solution constraint (oly-client = 2.0.3). Solution constraints that may result in a constraint on chef-client: [(chef-client = 8.0.1)], [(oly-client = 2.0.3) -> (chef-client = 8.0.2)]
Demand that cannot be met: (oly-client = 2.0.3)
Artifacts for which there are conflicting dependencies: chef-client = 8.0.1 -> [(cron >= 1.7.0), (logrotate >= 1.9.0), (windows >= 1.42.0)]Unable to find a solution for demands: chef-client (8.0.1), chef-sugar (3.4.0), compat_resource (12.19.0), cron (4.1.1), firewall (2.6.1), logrotate (2.1.0), ohai (5.0.4), oly-client (2.0.3), selinux (1.0.4), windows (3.0.5)
```

**metadata.rb**
```
depends 'selinux', '= 1.0.4'
depends 'firewall', '= 2.6.1'
depends 'chef-client', '= 8.0.2'
```
Even after removing `selinux` and `firewall` and modifying the cookbook, the issue still persits. This leaves the cookbook only having:
```
# Define the client intervals
node.default['chef_client']['interval'] = '900'
node.default['chef_client']['splay'] = '900'
# Define the chef server URL
node.default['chef_client']['server_url'] = 'https://engineering-chef-server.olympusat.tech/'

# Include the base cookbook
include_recipe 'chef-client::default'
``` 
and it gives the same error

**Comment by iennae** [comment]
Is the metadata.rb you've included for the oly-client cookbook? It looks like you might have a `Berksfile.lock` that you need to remove in order to do a successful berks install. can you try removing and rerunning to see if you are having the same issue?

**Comment by iennae** [comment]
Please reopen if you are still having problems after removing the Berksfile.lock.
