### ISSUE TITLE
Add ClearOS as part of the rhel platform_family

### ISSUE THREAD

**Issue by kmf** [chef-cookbooks/chef-client#494]
### Cookbook version
8.0.2

### Chef-client version
12.20.3

### Platform Details
ClearOS Community release 6.9.0 (Final)

### Scenario:
When I deploy the client, it doesn't install a service.

### Expected Result:
It should .... 
platform: clearos
platform_family: rhel

**Comment by iennae** [comment]
Can you provide more information about what is happening? Are you able to install the client and it just doesn't set up the service? Are you adding the service recipe to the run_list for the node?

**Comment by iennae** [comment]
I think the issue here is chef-client and not the cookbook itself.

**Comment by kmf** [comment]
Yes the client installs, however ... the OHAI data picks up that platform is clearos, this correct, however the platform_family should be rhel and not blank
![ohai-clearos](https://cloud.githubusercontent.com/assets/78700/26616915/614ae220-45d2-11e7-9d20-26c48356b547.png)

**Comment by iennae** [comment]
So this is most likely not an issue with this cookbook if clearos matches up with RHEL in terms of it's init systems. If it doesn't that's a separate issue. I've gone ahead and made a PR to Ohai that should ensure that the platform_family is mapped out correctly.

**Comment by iennae** [comment]
What package system does clearos use to install packages?

**Comment by kmf** [comment]
It uses rpm, and is built with RHEL sources

**Comment by kmf** [comment]
I have added an issue here https://github.com/chef/ohai/issues/1002

**Comment by iennae** [comment]
What init system does it use? 

Does it have locked down package sources that you can install from? https://github.com/chef-partners/chef-hipchat-plugin-cookbook/issues/3 looks like it has really old package content.

**Comment by lamont-granquist** [comment]
it does not usefully look like RHEL and is substantially stripped down so that a majority of rhel-based cookbooks will not work.  it should probably go under 'fedora'.  the only distros under 'rhel' should quack pretty much identically to `rhel` (scientific, centos, oracle).  and we just removed 'amazon' because it is not sufficiently similar.

**Comment by lamont-granquist** [comment]
(or maybe i'm wrong and it looks like its just recompiled centos and what i'm looking at is just the addon stuff that they sprinkle on top -- which would make it much more like a distro like oracle, where i could see that calling it `rhel` would be fine)

**Comment by lamont-granquist** [comment]
(or to be even clearer it looks like they use straight up centos and just customize a bit)

**Comment by kmf** [comment]
https://github.com/clearos/kernel

It's a CentOS Kernel

**Comment by kmf** [comment]
Is there anything else required from me?

**Comment by tas50** [comment]
This will ship with the next Ohai / Chef release and should just work
