### ISSUE TITLE
metadata.json "gem" ignored during a chef-client run

### ISSUE THREAD

**Issue by kkennedy1** [chef-cookbooks/chef-client#495]
### Cookbook version
AWS 6.1

### Chef-client version
12.20.3

### Platform Details
Windows Server 2012 R2 and Windows Server 2016

### Scenario:
Using the new AWS 6.1 cookbook downloaded from the Chef Supermarket, aws-sdk gems are not being pulled down during a chef-client run.

### Steps to Reproduce:
1. Install chef-client 12.20.3 either by upgrading from older version or fresh install.
2. By default, aws-sdk ruby gems are not installed (expected).
3. Using the aws_s3_file resource to download a file from an S3 bucket, you will get the following error: 

LoadError
---------
cannot load such file -- aws-sdk
Cookbook Trace:
---------------
c:/chef/cache/cookbooks/aws/libraries/s3.rb:16:in `s3_obj'
c:/chef/cache/cookbooks/aws/providers/s3_file.rb:29:in `do_s3_file'
c:/chef/cache/cookbooks/aws/providers/s3_file.rb:10:in `block in class_from_file' 

### Expected Result:
I would expect that the dependent aws-sdk gems get installed based on the "gems" entry in metadata.json.

### Actual Result:
What appears to be happening is the metadata.json is not respected during a chef-client run using a hosted chef server. IF we do a chef-zero run, metadata.json is respected and dependent gems listed (from metadata.json) are installed. We were able to pull metadata.rb from the AWS cookbook source (not from the Chef Supermarket), and simply replace metadata.json with metadata.rb and the dependent gems were installed successfully on a Windows server using hosted chef.

Please let me know if I can provide more information!

Thanks,

Kevin Kennedy

**Comment by tas50** [comment]
This repository is actually for the chef-client cookbook not the chef-client itself. It looks like you want to file this bug against the aws cookbook repository. File it there and I'll see what I can do.
