### ISSUE TITLE
Chef-Client fails restart after reducing ['chef_client']['interval'] attribute value

### ISSUE THREAD

**Issue by rosario-mattera** [chef-cookbooks/chef-client#497]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
7.1.0
### Chef-client version
[Version of chef-client in your environment]
12.18.31
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
RHEL 7.2
### Scenario:
[What you are trying to achieve and you can't?]
I've changed - from 7200 to 3600 - the default['chef_client']['interval']  attribute after the bootstrap of the nodes, and uploaded the cookbook to the chef server. At the first next execution, each node fails to restart the chef-client.
### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
Reduce the interval value after the bootstrap of the node.
### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
The chef-client restart works fine
### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
`#<Mixlib::ShellOut::ShellCommandFailed: service[chef-client] (chef-client::systemd_service line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '' ---- Begin output of /usr/bin/systemctl --system restart chef-client ---- STDOUT: STDERR: ---- End output of /usr/bin/systemctl --system restart chef-client ---- Ran /usr/bin/systemctl --system restart chef-client returned > had an error:
service[chef-client] (chef-client::systemd_service line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '' ---- Begin output of /usr/bin/systemctl --system restart chef-client ---- STDOUT: STDERR: ---- End output of /usr/bin/systemctl --system restart chef-client ---- Ran /usr/bin/systemctl --system restart chef-client returned
Description: Error executing action `restart` on resource 'service[chef-client]'
Mixlib::ShellOut::ShellCommandFailed
Expected process to exit with [0], but received ''
---- Begin output of /usr/bin/systemctl --system restart chef-client ----
STDOUT: 
STDERR: 
---- End output of /usr/bin/systemctl --system restart chef-client ----
Ran /usr/bin/systemctl --system restart chef-client returned 
Resource Declaration:
# In /var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb

 31: service 'chef-client' do
 32:   supports status: true, restart: true
 33:   action [:enable, :start]
 34: end
Compiled Resource:
# Declared in /var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb:31:in `from_file'

service("chef-client") do
  action [:enable, :start]
  supports {:status=>true, :restart=>true}
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  service_name "chef-client"
  enabled true
  running true
  pattern "chef-client"
  declared_type :service
  cookbook_name "chef-client"
  recipe_name "systemd_service"
end
Stacktrace
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/mixin/shell_out.rb:109:in `shell_out_with_systems_locale!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/service/systemd.rb:126:in `restart_service'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/service.rb:167:in `block in action_restart'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/service.rb:166:in `action_restart'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:127:in `run_delayed_notification'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:115:in `block in run_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:114:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:114:in `run_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:104:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'`

**Comment by dheerajd-msys** [comment]
Hi @rosario-mattera  Could you please check with latest cookbook. `chef-client` service is properly running after changing attribute `interval` from 7200 to 3600 .
## Platform & Chef client version
RHEL 7.2 / Chef Client v12.18.31

In order to verify I've followed the steps below : 
1. Run chef-client with recipe `chef-client`
_**Service is running**_
```
[azure@dh-rhel7 .chef]$ ps aux | grep chef
root      66849  5.0  0.6 251620 49096 ?        Ssl  10:05   0:00 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -c /etc/chef/client.rb -i 7200 -s 300
azure     66857  0.0  0.0 112712   972 pts/0    S+   10:05   0:00 grep --color=auto chef
[azure@dh-rhel7 .chef]$
```
2. Updated attribute 
```
[azure@dh-rhel7 .chef]$ cat attributes.json 
{
"chef_client":{"interval":"3600"}
}
```
3. Run chef-client 
Service is running with  interval updated.
```
[azure@dh-rhel7 .chef]$ ps aux | grep chef
root      67297  5.1  0.6 251532 50832 ?        Ssl  10:29   0:00 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -c /etc/chef/client.rb -i 3600 -s 300
azure     67305  0.0  0.0 112712   972 pts/0    S+   10:29   0:00 grep --color=auto chef
[azure@dh-rhel7 .chef]$
``` 

Closing this issue for now. Please let us know if there is anything.
