### ISSUE TITLE
chef_client_scheduled_task action :remove not working, wrong command

### ISSUE THREAD

**Issue by mdpdesign** [chef-cookbooks/chef-client#498]
### Cookbook version
8.1.2

### Chef-client version
12.19.36

### Platform Details
Windows (all)

### Scenario:
Trying to remove chef_client_scheduled_task by doing the :remove action

### Steps to Reproduce:
```
chef_client_scheduled_task 'Chef Client' do
    action :remove
end
```
### Expected Result:
chef-client Windows task should be removed.

### Actual Result:
Instead removing the task I got error:

```FATAL: Chef::Exceptions::ValidationFailed: chef_client_scheduled_task[Chef Client] (development::default line 16) had an error: Chef::Exceptions::ValidationFailed: Option action must be equal to one of: nothing, create, run, change, delete, end, enable, disable!  You passed :remove.```

### Solution:
`Change the action :remove in the file .\resources\scheduled_task.rb to action :delete`

```
action :remove do
  windows_task 'chef-client' do
    action :delete
  end
end
```

**Comment by tas50** [comment]
This should be fixed in 8.1.4. Thanks for the report
