### ISSUE TITLE
Chef-client uses iniparse gem with bug

### ISSUE THREAD

**Issue by voroniys** [chef-cookbooks/chef-client#500]
Chef: 12.20.3

Chef-client is using gem iniparse of version 1.4.2 which has a nasty bug. It is fixed in 1.4.3, so please update the gem and dependencies.

**Comment by tas50** [comment]
This repository is for the chef-client cookbook not chef itself. Additionally we upgrade the dependent gems before every release so chances are this has already been updated in Chef 13.0 or 13.1.

**Comment by voroniys** [comment]
But there are a lot of people who still using Chef 12

**Comment by tas50** [comment]
If there is another stable release of Chef 12 for security reasons then that gem will be brought in automatically
