### ISSUE TITLE
Configure rubygems_url from chef-client cookbook

### ISSUE THREAD

**Issue by OxHobbs** [chef-cookbooks/chef-client#502]
### Cookbook version
8.1

### Chef-client version
12.19.36-1

### Platform Details
Windows Server 2012 R2

### Scenario:
Configure the rubygems_url list setting in the client.rb file from the chef-client cookbook.  This setting was updated in the documentation at https://github.com/chef/chef-web-docs/pull/647.  This would be a great benefit for air-gapped environments that must use an internal rubygems server. There could be an attribute that maps to this setting; such as:

`default['chef_client']['rubygems_url'] = 'https://www.rubygems.org'`

**Comment by croffe** [comment]
You can configure the rubygems_url by setting the node.default['chef_client']['config']['rubygems_url'] and including chef-client::config

**Comment by iennae** [comment]
I've updated the documentation in PR #505 so that this is more clear. @croffe thanks for responding!

**Comment by iennae** [comment]
The README is updated for this now.
