### ISSUE TITLE
task recipe does not use find_chef_client method

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/chef-client#504]
### Cookbook version
8.1.6

### Chef-client version
12.14.89

### Platform Details
Windows Server 2012 R2

### Scenario:
Installing the chef-client as a Scheduled Task can have the wrong client bin path

### Steps to Reproduce:
In a role, set default_attributes section where `node['chef-client']['bin']` is a non-Windows path, like /opt/chef/bin/chef-client and run the chef-client::task recipe as part of the node's run list.

### Expected Result:
Looking at the following recipes: cron, all linux *_service recipes,  the chef-client cookbook leverages the `#find_chef_client` method to find the correct path, but the task recipe does not follow this precedence. Seeing the the find_chef_client method also supports hunting for the client bin in Windows, it seems logical to use this in the task recipe.

### Actual Result:
chef_client_scheduled_task resource called in the task recipe uses the node['chef-client']['bin'] value that hasn't been set by a search with `#find_chef_client`.

**Comment by iennae** [comment]
Thanks for reporting.

**Comment by tas50** [comment]
Merged to master
