### ISSUE TITLE
rubygems_url attribute not working

### ISSUE THREAD

**Issue by sputturao** [chef-cookbooks/chef-client#520]
### Cookbook version
8.1.8

### Chef-client version
12.19.36

### Platform Details
RHEL6.8 and RHEL7.3

### Scenario:
Gem update while upgrading chef package from 12.19.36 to 13.1.31.

### Steps to Reproduce:
Created a wrapper cookbook with chef_client_updater. Changed the following attributes:
default['chef_client_updater']['version'] = '13.1.31'
 default['chef_client_updater']['download_url_override'] = 'http://xyz123.com/chef-13.1.31-1.el6.x86_64.rpm'
 default['chef_client_updater']['checksum'] = '31d3c8d09a884a10f93d58c9ead636cfb19b12c9ea6c8de1bb661918347c164d'

The above cookbook updates mixlib gems during the upgrade. As we have a air-gapped environment, we have set a ruby gem mirror. And set the following attribute in chef-client cookbook.
default['chef_client']['config']['rubygems_url'] = 'http://xyz.com/'

Though the client.rb is already updated with rubygems_url, it still tries to connect to http://rubygems.org

### Expected Result:
rubygems_url in client.rb config should take into effect during the chef-client run but it is not.

### Actual Result:
Mixlib::ShellOut::ShellCommandFailed: chef_client_updater[update chef-client] (chef_client_updater::default line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem update --system --no-rdoc --no-ri ----
STDOUT:
STDERR: ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (**https://rubygems.org/specs.4.8.gz**)
---- End output of /opt/chef/embedded/bin/gem update --system --no-rdoc --no-ri ----

**Comment by iennae** [comment]
I don't think the problem is with the chef-client cookbook here. Which recipes are you including? Based on the output you have included it looks like the chef_client_updater is what is erroring. When I created a wrapper cookbook, I got a failure at trying to install (it didn't try to go to rubygems.org). I don't know whether chef_client_updater will honor the rubygems_url configuration. It's just using https://github.com/chef/mixlib-install. Can you verify your run_list/recipe contents? Thanks.

My wrapper recipe looked like:

> 
> node.default['chef_client_updater']['version'] = '13.1.31'
> node.default['chef_client_updater']['download_url_override'] = 'http://xyz123.com/chef-13.1.31-1.el6.x86_64.rpm'
> node.default['chef_client_updater']['checksum'] = '31d3c8d09a884a10f93d58c9ead636cfb19b12c9ea6c8de1bb661918347c164d'
> node.default['chef_client']['config']['rubygems_url'] = 'http://xyz.com/'
> 
> include_recipe 'chef-client::config'
> include_recipe 'chef-client'
> 
> chef_client_updater 'Install latest Chef' do
>   post_install_action 'kill'
> end

**Comment by sputturao** [comment]
Runlist has chef-client wrapper and chef-client-updater wrapper.

As per the details provided by Jeremy in the below link, rubygems_url should install the gems from the specified internal url. But in my case, it is trying to go to rubygems.org (external) and as we have a air-gapped environment, it is failing.

https://github.com/jeremymv2/chef-intranet-scaffolding#installing-additional-gems-via-chef-gem_package-resource-from-alternate-sources

**Comment by iennae** [comment]
What's in your chef-client wrapper?

**Comment by sputturao** [comment]
Default recipe with the following recipes:
include_recipe 'chef-client::config'
include_recipe 'chef-client::default'

Attributes:
default['chef_client']['interval']    = '1800'
default['chef_client']['log_dir']     = '/var/log/chef'
default['chef_client']['log_perm'] = '640'
default['chef_client']['config']['chef_server_url'] = 'https://xyz123.com/organizations/abc'
default['chef_client']['config']['rubygems_url'] = 'http://internalrubygems.com/'

**Comment by croffe** [comment]
@sputturao The issue here is with Chef Client 12. The rubygems_url functionality was enhanced with Chef Client 13.  It's been working for me once I updated these clients to Chef Client 13.  See the release notes: https://discourse.chef.io/t/chef-client-13-released/10735

**Comment by dheerajd-msys** [comment]
@sputturao Please check ^ and confirm.

Thanks!

**Comment by lamont-granquist** [comment]
Yeah this was never a cookbook bug, if the config is rendering properly this cookbook is working, if the behavior is still broken that is on chef-client.
