### ISSUE TITLE
Windows Task issue with 13.5.3 - undefined method `elements' for nil:NilClass 

### ISSUE THREAD

**Issue by croffe** [chef-cookbooks/chef-client#526]
### Cookbook version
8.1.8

### Chef-client version
13.5.3

### Platform Details
Windows 6.0.6002

### Scenario:
Configure Windows Task in Windows

### Steps to Reproduce:
include_recipe 'chef-client::config'
include_recipe 'chef-client::delete_validation'
include_recipe 'chef-client'

### Expected Result:
Windows Scheduled task will be maintained by cookbook (added or updated)

### Actual Result:
windows_task[chef-client] (C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb line 46) had an error: NoMethodError: undefined method `elements' for nil:NilClass

Log:
[log.txt](https://github.com/chef-cookbooks/chef-client/files/1407623/log.txt)

Stacktrace:
[stacktrace.txt](https://github.com/chef-cookbooks/chef-client/files/1407625/stacktrace.txt)

**Comment by tas50** [comment]
@croffe Am I right that you're trying to run this on Windows Vista? If so we don't support Windows Vista as it's no longer supported by Microsoft. I've tried to reproduce this on other Windows releases, but I'm not seeing the same failure.

**Comment by croffe** [comment]
No, this is Windows Server 2008 Enterprise SP2
Version 6.0 (Build 6002: Service Pack 2) x64

**Comment by tas50** [comment]
@croffe Looks like this is actually a bug in the windows_task resource itself. Can you give this one a try on Chef 13.6.4 and let me know if it's still an issue. Additionally if it's still a problem what language / date format is the system using?

**Comment by croffe** [comment]
Still an issue in 13.6.4, same line on scheduled_task.rb
Formats are set to English and M/d/yyyy (11/15/2017)

**Comment by croffe** [comment]
@tas50 I agree this looks like a bug in the windows_task resource itself.  I've logged a new issue https://github.com/chef/chef/issues/6585

**Comment by tas50** [comment]
Thanks for the chef/chef bug. I'll dig in there and see what I can do
