### ISSUE TITLE
Logrotate postrotate script incorrect for upstart hosts

### ISSUE THREAD

**Issue by atombaby** [chef-cookbooks/chef-client#527]
### Cookbook version
8.1.8

### Chef-client version
Demonstrated with 12.21.4 and 13.5.3

### Platform Details
Ubuntu Trusty (14.04 LTS)
Ubuntu Xenial (16.04 LTS) with upstart-sysv

### Scenario:

Rotating chef-client logs requires restarting a running daemon to reopen the log file.  This is typically done via a `postrotate` script that reloads or restarts the chef-client service using native service control tools (e.g. init scripts, sysctl, etc).  

The recipe `chef-client::config` will configure a job in `logrotate.d` that does this- however, on systems using Upstart, the postrotate script incorrectly specifies an init script for reloading the service:

```
"/var/log/chef/client.log" {
  weekly
  rotate 12
  compress
  postrotate
    /etc/init.d/chef-client reload >/dev/null || :
  endscript
}
```

This despite explicitly declaring `init_style` as `upstart` for the node.  The debug logs in a test-kitchen run suggest that the `init_style` attribute is correctly set:

```
    "chef_client": {
      "config": {
        "chef_server_url": "chefzero://localhost:8889",
        "validation_client_name": "chef-validator",
... output trimmed ...
      },
      "init_style": "upstart",
      "run_path": "/var/run/chef",
      "cache_path": "/var/cache/chef",
      "backup_path": "/var/lib/chef",
      "log_rotation": {
        "options": [
          "compress"
        ],
        "prerotate": null,
        "postrotate": "/etc/init.d/chef-client reload >/dev/null || :"
```

### Steps to Reproduce:
 1. Create a cookbook that depends on chef-client
 1. Create an attributes file that sets the `init_style` to `upstart`:
     `node.default['chef_client']['init_style'] = 'upstart'`
 1. Create a default recipe that includes the service and config recipes:
     `include_recipe "chef-client::service"`
     `include_recipe "chef-client::config"`
 1. Converge an Ubuntu 14.04 client
 1. Examine contents of `/etc/logrotate.d/chef-client`

### Expected Result:
The postrotate script in `/etc/logrotate.d/chef-client` uses `initctl` to reload the service:

```
  postrotate
    initctl reload chef-client >/dev/null || :
  endscript
```

### Actual Result:
The postrotate script in `/etc/logrotate.d/chef-client` uses an init script to reload the chef client:

```
  postrotate
    /etc/init.d/chef-client reload >/dev/null || :
  endscript
```

The logrotate config file correctly uses `sysctl` on systemd hosts (e.g. Xenial).  However, when I revert a Xenial host back to upstart (via installation of the `upstart-sysv` package), I'm getting the same behavior (i.e. the postrotate action is `/etc/init.d/chef-client`).

I am able to work around this by adding an attribute for Upstart based systems that explicitly declares the correct postrotate action:

```
  chef_client:
    log_rotation:
      postrotate: initctl restart chef-client >/dev/null || :
```

But it seems to me that the expected behavior for the cookbook would be to install the upstart script when `init_style` is set to `upstart`.

Thanks for looking at this.

**Comment by atombaby** [comment]
Upon further review, this may not be a problem with the cookbook, rather the computed OHAI value for `init_package` in Trusty.  A [bug](https://github.com/chef/ohai/issues/917) has been filed indicating that the default mechanism for calculating this attribute is inadequate for Trusty:

> init_package should report upstart, but it reports init. the contents of /proc/1/cmdline is not enough for determining the init system:

This is slated to be improved in Ohai 14.  I'll leave it to the maintainers how to handle this issue: I'm fine either way and as this is largely an upstream bug, I'm happy to work around it locally until Ohai 14 or until we've upgraded all our Trusty hosts.

**Comment by majormoses** [comment]
I see this bug even forcing updating the `init_style` in my cookbook:
```
chef (12.21.20)> node['chef_client']['init_style']
 => "sysytemd" 
chef (12.21.20)> node['chef_client']['log_rotation']['postrotate']
 => "/etc/init.d/chef-client reload >/dev/null || :"
```

Taking a look it appears to be order of operations with the attributes: https://github.com/chef-cookbooks/chef-client/blob/v9.0.2/attributes/default.rb#L171 if you are doing this then you likely need to also update the post_rotate as well. If you are wondering why we are doing this there are essentially 2 reasons:
- transition from runit to `(upstart|systemd)` depending on the node platform version.
- ohai detection of init subsystems is at best buggy

I will report back if that solves my issue.

**Comment by majormoses** [comment]
Yup resetting it explicitly in the same place I am checking the platform fixes it. I will look to see if there is a relatively low impact to the cookbook change in order to fix this.

**Comment by majormoses** [comment]
Ya the way to fix this is to make these not node attributes and make them `(attributes|properties)` in a `(lwrp|custom resource)`.

**Comment by dheerajd-msys** [comment]
@atombaby We've checked with cookbook **_v11.4.0_**  and verified that content of `/etc/logrotate.d/chef-client` is same as expected.
In order to verify we've followed the steps as depicted description.
1. In Ubuntu 16.04 installed `upstart-sysv`
2. Included run list
```
include_recipe "chef-client::service"
include_recipe "chef-client::config"
```
3. After chef-client run content of `/etc/logrotate.d/chef-client`
```
azure@dh-ubu16-azure:~/chef-repo/.chef$ cat /etc/logrotate.d/chef-client 
# This file was generated by Chef for dh-ubu16-azure.itym0qvvov0ulf4kbnwt4pkehb.xx.internal.cloudapp.net.
# Do not modify this file by hand!

"/var/log/chef/client.log" {
  weekly
  rotate 12
  compress
  postrotate
    initctl reload chef-client >/dev/null || :
  endscript
}

```
## Ohai version
```
azure@dh-ubu16-azure:~/chef-repo/.chef$ ohai -v
Ohai: 13.5.0
```

Please check with latest cookbook and let us know if there is anything.
Closing as it is working as expected with latest cookbook.
