### ISSUE TITLE
Passing $OPTIONS through systemd

### ISSUE THREAD

**Issue by directionless** [chef-cookbooks/chef-client#531]
### Cookbook version
master / v9.0.0

### Platform Details
Ubuntu with systemd timers

### Scenario:

I'm trying to decrease logs. I'd like to do this by passing the `--format` command line. I don't see a way to pass that through systemd timers.

I can see that that command line is being set to [`-c $CONFIG $OPTIONS`](https://github.com/chef-cookbooks/chef-client/blob/af3011631ec35e5035b360e18efddd02d7232b1d/recipes/systemd_service.rb#L23)

And `$OPTIONS` would normally come from the `EnvironmentFile`.

But, it looks like that file is generated by (chef-client.erb)[https://github.com/chef-cookbooks/chef-client/blob/c9d0a53716d9e7c30298f35259fb2d96b3f42873/templates/default/debian/default/chef-client.erb], which doesn't have any way to pass additional options in.

**Comment by directionless** [comment]
Well, I could embed newlines into splay, but that's just wrong.

**Comment by rmoriz** [comment]
In general I would highly welcome a way to customize ALL unit details using attributes.

**Comment by sanga1794** [comment]
Hi @directionless, you can pass additional options using node['chef_client']['daemon_options']

**Comment by sanga1794** [comment]
It is fixed in https://github.com/chef-cookbooks/chef-client/commit/93cd5854dcdb54ad736085f3dcc9ce733dd9a78f

**Comment by dheerajd-msys** [comment]
Thanks @sanga1794 for looking into this.

Closing this issue.
