### ISSUE TITLE
dsc_resource bails with PowershellCmdletException on Windows host with non standard winrm port

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef-client#537]
### Cookbook version
All

### Chef-client version
Chef 12.x & 13.x

### Platform Details
Windows

### Scenario:
`dsc_resource` cannot operate on a system that's running winrm on a non standard port.

### Steps to Reproduce:
Create a Windows systems, follow all the steps to configure winrm such that you can bootstrap the node. Now change the port on which winrm listens on the host to be something else than `5985`, try to run chef-client on the node now. When the convergence hits a `dsc_resource` the client run will bail with the error below.

### Expected Result:
`dsc_resource` executes properly irrespective of the port on which winrm is listening.

### Actual Result:
Chef::Exceptions::PowershellCmdletException
-------------------------------------------
Powershell Cmdlet failed: The client cannot connect to the destination specified in the request. Verify that the service on the destination is 
running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the 
destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the 
destination to analyze and configure the WinRM service: "winrm quickconfig".
     + CategoryInfo          : ConnectionError: (root/Microsoft/...gurationManager:String) [], CimException
     + FullyQualifiedErrorId : HRESULT 0x80338012
     + PSComputerName        : localhost

**Comment by smurawski** [comment]
@Sauraus As I mentioned in Slack, this issue is more appropriate for the https://github.com/chef/chef project.  This cookbook doesn't have anything to do with the `dsc_resource` resource.

**Comment by Sauraus** [comment]
Filed issue with Chef project here: https://github.com/chef/chef/issues/6657
