### ISSUE TITLE
chef-client ArgumentError: invalid date on Windows 

### ISSUE THREAD

**Issue by skares** [chef-cookbooks/chef-client#538]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
9.0.2
### Chef-client version
[Version of chef-client in your environment]
13.6.4
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Windows 2016, Windows 10, Windows 2012R2
### Scenario:
[What you are trying to achieve and you can't?]
We wanted the run the chef-client on Windows as Scheduled Task
### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
I think is was an issue an previous versions, but now this seems to be back again. The first chef-client run on Windows is successful and the chef-client scheduled task is created. Every chef run after this fails. 

ne 47) had an error: ArgumentError: invalid date
PS C:\Windows\system32> chef-client
Starting Chef Client, version 13.6.4
resolving cookbooks for run list: ["cm_it_windows_chef-client", "cm_it_windows-baseconfig", "cm_it_windows-nxlog", "cm_i
t_windows-nsclient", "cm_it_windows-telegraf", "cm_it_core-chef-client-updater"]
Synchronizing Cookbooks:
  - cm_it_windows_chef-client (0.1.1)
  - chef-client (9.0.2)
  - cron (5.0.1)
  - logrotate (2.2.0)
  - windows (3.4.1)
  - ohai (5.2.0)
  - cm_it_windows-nxlog (0.1.1)
  - cm_it_windows-nsclient (0.1.0)
  - cm_it_windows-telegraf (0.1.3)
  - cm_it_core-chef-client-updater (0.1.4)
  - chef_client_updater (3.1.2)
  - cm_it_windows-baseconfig (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 37 resources
Recipe: chef-client::delete_validation
  * file[C:\chef\validation.pem] action delete (up to date)
Recipe: chef-client::task
  * windows_service[chef-client] action configure_startup (skipped due to only_if)
  * chef_client_scheduled_task[Chef Client] action add
    * windows_task[chef-client] action create

      ================================================================================
      Error executing action `create` on resource 'windows_task[chef-client]'
      ================================================================================

      ArgumentError
      -------------
      invalid date

      Resource Declaration:
      ---------------------
      # In C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb

       47:   windows_task 'chef-client' do
       48:     run_level :highest
       49:     command "cmd /c \"#{client_cmd}\""
       50:     user               new_resource.user
       51:     password           new_resource.password
       52:     frequency          new_resource.frequency.to_sym
       53:     frequency_modifier new_resource.frequency_modifier
       54:     start_time         new_resource.start_time || start_time
       55:     start_day          new_resource.start_date unless new_resource.start_date.nil?
       56:   end
       57: end

      Compiled Resource:
      ------------------
      # Declared in C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb:47:in `block in class_from_file'

      windows_task("chef-client") do
        action :create
        default_guard_interpreter :default
        task_name "chef-client"
        declared_type :windows_task
        cookbook_name "chef-client"
        run_level :highest
        command "cmd /c \"C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300\""
        user "SYSTEM"
        password nil
        frequency :minute
        frequency_modifier 30
        start_time "11:12"
        execution_time_limit "PT72H"
        start_day "11.12.2017"
      end

      System Info:
      ------------
      chef_version=13.6.4
      platform=windows
      platform_version=10.0.14393
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
      program_name=C:/opscode/chef/bin/chef-client
      executable=C:/opscode/chef/bin/chef-client

    ================================================================================
    Error executing action `add` on resource 'chef_client_scheduled_task[Chef Client]'
    ================================================================================

    ArgumentError
    -------------
    windows_task[chef-client] (C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb line 47) had an error: Ar
gumentError: invalid date

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/chef-client/recipes/task.rb

     37: chef_client_scheduled_task 'Chef Client' do
     38:   user node['chef_client']['task']['user']
     39:   password node['chef_client']['task']['password']
     40:   frequency node['chef_client']['task']['frequency']
     41:   frequency_modifier lazy { node['chef_client']['task']['frequency_modifier'] }
     42:   start_time node['chef_client']['task']['start_time']
     43:   start_date node['chef_client']['task']['start_date']
     44:   splay node['chef_client']['splay']
     45:   config_directory node['chef_client']['conf_dir']
     46:   log_directory node['chef_client']['log_dir']
     47:   chef_binary_path node['chef_client']['bin']
     48:   daemon_options node['chef_client']['daemon_options']
     49: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/chef-client/recipes/task.rb:37:in `from_file'

    chef_client_scheduled_task("Chef Client") do
      action [:add]
      default_guard_interpreter :default
      declared_type :chef_client_scheduled_task
      cookbook_name "chef-client"
      recipe_name "task"
      user "SYSTEM"
      password nil
      frequency "minute"
      frequency_modifier 30
      start_time nil
      start_date nil
      splay "300"
      config_directory "C:/chef"
      log_directory "C:/chef/log"
      chef_binary_path "C:/opscode/chef/bin/chef-client"
      daemon_options []
    end

    System Info:
    ------------
    chef_version=13.6.4
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

Running handlers:
[2017-12-11T10:42:50+01:00] ERROR: Running exception handlers
Running handlers complete
[2017-12-11T10:42:50+01:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds
[2017-12-11T10:42:50+01:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2017-12-11T10:42:50+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-12-11T10:42:50+01:00] FATAL: ArgumentError: chef_client_scheduled_task[Chef Client] (chef-client::task line 37) ha
d an error: ArgumentError: windows_task[chef-client] (C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb li
ne 47) had an error: ArgumentError: invalid date
PS C:\Windows\system32>

**Comment by cheeseplus** [comment]
This is an upstream issue in chef-client and the related PR for it is https://github.com/chef/chef/pull/6628

**Comment by tas50** [comment]
@skares We're currently working on a series of fixes in the chef-client itself for the 13.7 release that cleanup the windows_task resource. We added a large amount of data validation to the properties, fixed idempotency issues, improved debug logging, and resolves failures when the system clock is set to non-US date format. It looks like what we have so far will resolve your issues with this cookbook so hang in there, we're working to clean this all up.

**Comment by reidca** [comment]
I am also seeing the exact same issue and this is using the latest version of the chef-client (10.0.1) cookbook which i downloaded to the chef server today. Is there a fix to this issue?

We also upgraded the chef server. Any thoughts as to what this issue is caused by?
