### ISSUE TITLE
encrypted_data_bag_secret setting in client.rb on Windows 2016 broken

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef-client#544]
### Cookbook version
9.0.2 ( > 6 )

### Chef-client version
12.x & 13.x

### Platform Details
Windows 2016 SRV

### Scenario:
include_recipe chef-client::config in your base or some other cookbook

### Steps to Reproduce:
Bootstrap the windows node with ```knife bootstrap ........ --secret-file ~/.chef/encrypted_data_bag_secret```

### Expected Result:
client.rb will contain a reference to c:\chef\encrypted_data_bag_secret

### Actual Result:
```encrypted_data_bag_secret "/etc/chef/encrypted_data_bag_secret"```

**Comment by lamont-granquist** [comment]
You have to set the `node['chef_client']['config']['encrypted_data_bag_secret']`, there's no magic wiring between this cookbok and bootstrap like that.
