### ISSUE TITLE
chef-client output is being written to log file when log_location is set to :win_evt

### ISSUE THREAD

**Issue by rdean716** [chef-cookbooks/chef-client#556]
### Cookbook version
chef-client@9.0.5

### Chef-client version
Chef: 13.6.4

### Platform Details
Windows Server 2012 R2

### Scenario:
After setting log location to :win_evt, we expected the chef-client to output only to the windows event log.  But, we're seeing run output in both the windows event log and in \chef\log\client.log.  Note that we are running the chef-client as a scheduled task.

### Steps to Reproduce:

Override the log_location attribute
```
node.override['chef_client']['config']['log_location'] = ':win_evt'
include_recipe 'chef-client::config'
```

renders the following in \chef\client.rb:
```
...
log_location ":win_evt"
...
```

### Expected Result:
We expect to stop seeing the output from the chef-client in \chef\log\client.log

### Actual Result:
Output is being written to both \chef\log\client.log and the windows event log.

**Comment by tas50** [comment]
This has been fixed on master. thanks for the report
