### ISSUE TITLE
Test that systemd timer configuration is working

### ISSUE THREAD

**Issue by mattouille** [chef-cookbooks/chef-client#557]
### Cookbook version
10.0.0

### Chef-client version
13.7.16

### Platform Details
Ubuntu 16.04

### Scenario:
Determine if timers are set correctly according to the SystemD spec

given chef-client.timer
then /etc/systemd/system/chef-client.timer exists (another systemd unit file) exists
then /etc/systemd/system/chef-client.service exists
then /etc/systmd/system/chef-client.timer Interval should correlate to attribute
then /etc/systmd/system/chef-client.timer SPlay should correlate to attribute
then chef-client.service IS installed
then chef-client.service IS NOT enabled
then chef-client.service IS NOT running

### Steps to Reproduce:
Set attributes 

```
default['chef-client']['init_style'] = 'systemd'
default['chef_client']['systemd']['timer'] = true
```

### Expected Result:
Tests run according to the above scenario

### Actual Result:
No tests are currently done

### Note:
The functionality is working, but it's working on a hope basis. No test is being run to determine the actual outcome, therefore, changes in SystemD could potentially break this cookbook.

**Comment by dheerajd-msys** [comment]
This issue is fixed in https://github.com/chef-cookbooks/chef-client/pull/614.

@mattouille Please close this issue.
