### ISSUE TITLE
Not possible to configure multiple scheduled tasks on windows (like at boot time and on a schedule)

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef-client#558]
Before I go and implement a solution to this I'd like to hear from others how they'd like to see this fixed.

The current `task` attribute setup only allows you to define a single scheduled task which limits significantly when chef-client is run for example you cannot have chef-client run at boot time and a schedule.

https://github.com/chef-cookbooks/chef-client/blob/4ee4d1c3231b1e8add506aec47a461e534d85a85/attributes/default.rb#L69

The simplest solution to this would be to make the `task` attribute an array, but that would break backwards compatibility in major way.

Another option would be to declare a separate windows_task for one of the schedules, but that would kind of defy the purpose of having a cookbook to configure chef-client if it can't be used to configure chef-client in its entirety.

**Comment by tas50** [comment]
@Sauraus Have you looked at using the resource directly. The goal of the recipe is really to support the most basic use case. As soon as you deviate from a pretty simple setup you should really just write a wrapper cookbook using the resource itself.

**Comment by Sauraus** [comment]
That is a very valid point, let me look into that. :)

**Comment by dheerajd-msys** [comment]
@tas50 This requires closure as it's fixed.

Thanks!!
