### ISSUE TITLE
Chef client scheduled task invalid parameter error

### ISSUE THREAD

**Issue by bwhitacrejha** [chef-cookbooks/chef-client#575]
### Cookbook version
10.0.5

### Chef-client version
14.1.1

### Platform Details
Windows Server 2012r2

### Scenario:
Trying to utilize the 'task' recipe to create the Windows Scheduled task to execute the regular Chef-Client runs

### Steps to Reproduce:
simply using an include_recipe 'chef-client::task' in a recipe, for testing I used the default chef-client cookbook attributes.

### Expected Result:
The chef-client scheduled task should be able to run on the defined schedule without error

### Actual Result:
The chef-client scheduled task fails.  The message: 'The parameter is incorrect. (0x80070057)'

### Additional Info:
Extracting the exact syntax of the scheduled task action and replacing the /c with a /k for visibility:

cmd /k 'C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300'

And executing via a Start>Run, I received the following error:
''C:' is not recognized as an internal or external command, operable program or batch file.

On lines 49 thru 53 of the scheduled_task.rb Resource, there is a conditional that determines where to use single tick versus double quotes around the client_cmd content if the chef-client version is greater than 13.7. Based on that conditional, the logic is doing as it is been told and using single ticks.

However if I take the same logic I did earlier and wrap it in double quotes instead:
cmd /k "C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300"

It executes fine.  So I am not sure what changed in Chef-Client 13.7 to require this logic be added to this resource, but it would appear that with Chef-Client 14.1.1. this logic is no longer needed and double quotes are what is needed again for this to function.

**Comment by darko-mesaros** [comment]
+1 on this issue. The way I made it work (only temp tho) is by moving all the parameters after `cmd` to the Parameter section of the scheduled task. 
That being said, this issue has been fixed in the cookbook version `10.0.5`.

**Comment by bwhitacrejha** [comment]
Confirmed this is resolved in version 10.0.5. My initial reports were inaccurate. I was experiencing the issue with version 10.0.4.
