### ISSUE TITLE
Issue with content method in 10.0.5?

### ISSUE THREAD

**Issue by jmtaylor90** [chef-cookbooks/chef-client#576]
### Cookbook version
10.0.5

### Chef-client version
tested with versions:
chef_version=14.1.12
chef_version=14.2.0

### Platform Details
centos-release-7-5.1804.el7.centos.2.x86_64

### Scenario:
attempting to run chef-client cookbook

### Steps to Reproduce:
run chef-client with chef-client cookbook in run list

### Expected Result:
expect chef-client run to complete successfully

### Actual Result:
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/chef-client/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `content' for ChefSystemdCookbook::UnitResource

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb:66:in `block in from_file'
  /var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb:65:in `from_file'
  /var/chef/cache/cookbooks/chef-client/recipes/service.rb:39:in `from_file'
  /var/chef/cache/cookbooks/chef-client/recipes/default.rb:23:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb:

 59:  
 60:  if node['chef_client']['systemd']['timeout']
 61:    service_unit_content['Service']['TimeoutSec'] =
 62:      node['chef_client']['systemd']['timeout']
 63:  end
 64:  
 65:  systemd_unit 'chef-client.service' do
 66>>   content service_unit_content
 67:    action :create
 68:    notifies(:restart, 'service[chef-client]', :delayed) unless timer
 69:  end
 70:  
 71:  service 'chef-client' do
 72:    supports status: true, restart: true
 73:    action(timer ? [:disable, :stop] : [:enable, :start])
 74:  end
 75:  

System Info:
------------
chef_version=14.2.0
platform=centos
platform_version=7.5.1804
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/bin/chef-client
executable=/opt/chef/bin/chef-client

Running handlers:
[2018-06-08T13:53:41+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-06-08T13:53:41+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds
[2018-06-08T13:53:41+00:00] WARN: Using deprecated positional arguments for sign(), please update to keyword arguments (from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/http/authenticator.rb:114)
[2018-06-08T13:53:41+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-06-08T13:53:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-06-08T13:53:41+00:00] FATAL: NoMethodError: undefined method `content' for ChefSystemdCookbook::UnitResource

**Comment by rdubya16** [comment]
@jmtaylor90 Did you find a solution to this? Seeing the same thing when I installed systemd for my wrapper class. I see this is closed.

**Comment by jmtaylor90** [comment]
If I am remembering right, it was on my end with some version pinning/conflicts. I don't recall the specifics now unfortunately but it was definitely on my end.
