### ISSUE TITLE
"env" resource : Incorrect mumber of arguments (fails at compile stage)

### ISSUE THREAD

**Issue by vishalbasra** [chef-cookbooks/chef-client#579]
https://github.com/chef-cookbooks/chef-client/blob/57e8b9741f1d0f92ca5c20b2a80289b4a2bef50f/libraries/helpers.rb#L91
### Cookbook Version
10.1.0

### Chef-client version
13.8.5

### Platform Details
Windows(2008 / 2012 / 2016)

**Scenario**
Using the env resource referring to the documentation here https://docs.chef.io/resource_windows_env.html errors out like this 
```
ArgumentError 
-------------
wrong number of arguments (given 1, expected 0)
```
While in the stack-strace 
```
ArgumentError: wrong number of arguments (given 1, expected 0)
C:/chef/cache/cookbooks/chef-client/libraries/helpers.rb:91:in env
```

### Steps to reproduce 
Use the env resource as described in the documentation 
```
env ‘MY_FILE’ do
  action :create
  value ‘myvalue’
end
```

### Expected outcome 
This should work 

### Additional info
Calling the env resource like this *does not* error out but this is no-where in the documentation.
```
env do
  action :create
  value ‘myvalue’
end
```

### Known cookbook version where this used to work 
`10.0.5`

**Comment by Brantone** [comment]
FYI : related to https://github.com/windowschefcookbooks/visualstudio/issues/28 also discussed in Slack channel where @RyanFrantz was made aware. Relates to this commit: https://github.com/chef-cookbooks/chef-client/commit/44ce88bc06749ecef859c3551d4235617c93d321#diff-38a4aeddb4e620724d3b85362cb8b939

**Comment by jcruzfrontline** [comment]
Ping.  Is there anything we can do to bypass this in the mean time?

**Comment by Annih** [comment]
The version 10.1.0 is clearly buggy and breaking normal chef runs without easy workaround, @tas50 could we have a quick release of any fix for this issue? (#580 seems OK)

**Comment by jcruzfrontline** [comment]
@Brantone  - Can we get this merged?

**Comment by Brantone** [comment]
Looks like the ball is in @tas50  's court.

**Comment by jcruzfrontline** [comment]
@tas50  - Can you assist us with this?

**Comment by Annih** [comment]
@vishalbasra I think you can close this issue, thanks @tas50 for the quick release of *1.0.1.1* & *1.0.1.2*

**Comment by dheerajd-msys** [comment]
@tas50 This issue could be closed now as it's fixed in https://github.com/chef-cookbooks/chef-client/pull/580.
