### ISSUE TITLE
chef-client cookbook removes policyfile settings from client.rb

### ISSUE THREAD

**Issue by trickyearlobe** [chef-cookbooks/chef-client#588]
### Cookbook version
11.0.0

### Chef-client version
14.3.37

### Platform Details
CentOS6

### Scenario:
My customer wants to use the chef-client cookbook in conjunction with policyfiles and for robustness they want to put the policyname/group in the client.rb

If we use the `policy_group` and `policy_name` in the `client.rb` those settings get obliterated when we run the `config` recipe.

**Comment by dheerajd-msys** [comment]
Per analysis and comment https://github.com/chef/chef/pull/8929#issuecomment-552869460 it is won't fix issue.

So closing this now.
