### ISSUE TITLE
Setting daemon_options causes the options to appear twice in systemd unit files

### ISSUE THREAD

**Issue by joerg** [chef-cookbooks/chef-client#594]
### Cookbook version

11.0.1

### Chef-client version

14.1.12

### Platform Details

RedHat 7

### Scenario:

When setting daemon_options the chef-client daemon is started with the parameters passed twice.
In https://github.com/chef-cookbooks/chef-client/blob/master/recipes/systemd_service.rb#L50
```
exec_options = if timer
                 '-c $CONFIG $OPTIONS'
               else
                 '-c $CONFIG -i $INTERVAL -s $SPLAY $OPTIONS'
end

service_unit_content = {
    ...
    'ExecStart' => "#{client_bin} #{exec_options} #{node['chef_client']['daemon_options'].join(' ')}",
    ...
}
```

It is clear that $OPTIONS from sysconfig and daemon_options are used. Since the environment file $OPTIONS are used for init.d and others too daemon_options should be removed here.

When daemon_options are setting the formatter this causes duplicate log output due to this bug: https://github.com/chef/chef/issues/7737

### Steps to Reproduce:

Set any daemon_options and the daemon is started with these options duplicated.

### Expected Result:

Options should appear only once.

### Actual Result:

See https://github.com/chef/chef/issues/7737

**Comment by Annih** [comment]
@joerg your review has been merged maybe you can close this issue :)

Cc. @tas50
