### ISSUE TITLE
PATH setting for cmd.exe execution assumed, not specified

### ISSUE THREAD

**Issue by sean-horn** [chef-cookbooks/chef-client#601]
### Cookbook version
11.0.3

### Chef-client version
Chef Client 14.x

### Platform Details
RHEL 6.x, 7.x

### Scenario:
Minor security issue

### Steps to Reproduce:
N/A

### Expected Result:
The known path for cmd.exe on a windows system should be specified to avoid nefarious PATH settings

### Actual Result:
cmd.exe is called directly, assuming that the PATH will be set to the known OS location.

Here's the non absolute path call to cmd
https://github.com/chef-cookbooks/chef-client/blob/master/resources/scheduled_task.rb#L47-L51

**Comment by dheerajd-msys** [comment]
@sean-horn @tas50 Please close this as it is fixed in https://github.com/chef-cookbooks/chef-client/pull/605 .
