### ISSUE TITLE
masking chef-client in systemd doesnt work

### ISSUE THREAD

**Issue by theundefined** [chef-cookbooks/chef-client#615]
### Cookbook version
[4.3.1]

### Chef-client version
[12.22.5]

### Platform Details
[Debian/8, Ubuntu 16.04, Ubuntu 18.04]

### Scenario:
I want to mask chef-client service on systemd to disable it and forbid to start.

### Steps to Reproduce:
```
root@vagrant-ubuntu-1804:~# systemctl mask chef-client.service 
Failed to mask unit: File /etc/systemd/system/chef-client.service already exists.
```

### Expected Result:
I expect chef-client to be masked

### Actual Result:
chef-client can't be masked, because systemd configuration is in /etc/systemd/system/chef-client.service. I think it should be in /lib/systemd/system - then masking would work fine.
I see that it's created in https://github.com/chef-cookbooks/chef-client/blob/master/recipes/systemd_service.rb#L65, what depends on https://github.com/chef/chef/blob/master/lib/chef/provider/systemd_unit.rb#L207

On the other hand - i see that masking systemd units is provided by chef (https://github.com/chef/chef/blob/master/lib/chef/provider/systemd_unit.rb#L119) - but i can't imagine how it should work (?)

**Comment by Vasu1105** [comment]
May be this will help https://docs.chef.io/resource_systemd_unit.html

**Comment by theundefined** [comment]
Hm.. I want to disable chef-client for a machine. Not write recipe ;) I know that i can disable it by not including 'chef-client::default' recipe - but i think it's not a good solution.

**Comment by lamont-granquist** [comment]
not a bug with this cookbook, it is an enhancement request against core-chef's systemd_unit:  chef/chef#9093
