### ISSUE TITLE
Spurious code in client.rb if handlers not defined

### ISSUE THREAD

**Issue by trickyearlobe** [chef-cookbooks/chef-client#646]
### Cookbook version
11.5.0

### Chef-client version
15.x

### Platform Details
RHEL 7.6

### Scenario:
Customer is using the `chef-client` cookbook to maintain the `client.rb` on all nodes
After a recent update, the cookbook is adding un-needed code to the `client.rb`

The code looks like:-

```
# Do not crash if a handler is missing / not installed yet
begin
rescue NameError => e
  Chef::Log.error e
end
```

Seems to be related to this change
https://github.com/chef-cookbooks/chef-client/commit/62579ccbee1dc30c5abd5a2f92aa16ecfcf0981c#diff-3a090d01433d142e84af2c33eeab49b5L54

**Comment by trickyearlobe** [comment]
Forgot to add, the customer has no handlers defined :)

**Comment by dheerajd-msys** [comment]
Fixed in https://github.com/chef-cookbooks/chef-client/pull/645
