### ISSUE TITLE
Running task scheduler as non system user

### ISSUE THREAD

**Issue by suniilsync** [chef-cookbooks/chef-client#671]
### Cookbook version
Latest

### Chef-client version
14.14.29

### Platform Details
windows 10

### Scenario:
We want to run a chef-client in the windows machine as non-systemuser (devtools user),  but when we set the user attribute, I get the following error.

           Error executing action `add` on resource 'chef_client_scheduled_task[Chef Client]'
           ================================================================================

           ArgumentError
           -------------
           Please provide a password or check if this task needs to be interactive! Valid passwordless users are: 'SYSTEM', 'NT AUTHORITY\SYSTEM', 'LOCAL SERVICE', 'NT AUTHORITY\LOCAL SERVICE', 'NETWORK SERVICE', 'NT AUTHORITY\NETWORK SERVICE', 'ADMINISTRATORS', 'BUILTIN\ADMINISTRATORS', 'USERS', 'BUILTIN\USERS', 'GUESTS', 'BUILTIN\GUESTS'

### Steps to Reproduce:
set the following attributes 

default['chef_client']['task']['user'] = 'devtools'

### Expected Result:
chef-client task scheduler task should run as devtools users, not an SYSTEM user

### Actual Result:

Now chef-client user runs as SYSTEM in this case, from the master node, if check the chef-client node status, it says never run.

so we should run the chef-client in task scheduler as devtools user.

**Comment by tas50** [comment]
You need to provide a password in order to use an account other than system.

**Comment by suniilsync** [comment]
Thanks, it worked
