### ISSUE TITLE
Chef client config reload does not work across multiple kitchen converges

### ISSUE THREAD

**Issue by jjustice6** [chef-cookbooks/chef-client#686]
## The problem statement

When you do `kitchen converge`, you expect the same result to happen every time.

## The breakdown

Due to [this chunk of code](https://github.com/chef-cookbooks/chef-client/blob/v11.5.0/recipes/config.rb#L80-L99), Chef::Config reloading does not happen across multiple kitchen runs.

First run: `"#{node['chef_client']['conf_dir']}/client.rb"` is written, causing the config to reload. Everything works as expected. 

Subsequent runs: On a real machine, the subsequent runs of chef load from that chef client conf dir, so there's no need to reload - the fact that the config file is unchanged proves it, since chef is loading up the config from that file at launch anyway.

Except in Test Kitchen. Because in Test Kitchen, subsequent converges launch with the config from `/tmp/kitchen/client.rb` rather than the client.rb out of the conf_dir.

This means that you do not get consistent behavior if you attempt to perform integration testing across multiple runs in which the cookbook under test cares about Chef::Config values for some reason.

## Potential Fixes

A rather trivial workaround would be to change this block of code:

```
  if node['chef_client']['reload_config']
    notifies :run, 'ruby_block[reload_client_config]', :immediately
  end
```
to the following:

```
  if node['chef_client']['reload_config'] || ENV['TEST_KITCHEN']
    notifies :run, 'ruby_block[reload_client_config]', :immediately
  end
```
but I'm aware there is a lot of resistance to the pattern of calling out Test Kitchen and doing something different. 

A user who encounters this issue could of course invoke `Chef::Config.from_file("#{node['chef_client']['conf_dir']}/client.rb") if ENV['TEST_KITCHEN']` themselves after doing `include_recipe 'chef-client::config'` so that it doesn't require dirtying up this cookbook with that pattern; but it isn't immediately obvious that this is necessary. (In our case, when encountering this issue we wound up tracking through several other parts of our system before we realized the config attribute itself was the problem.) (It's also possible that using Chef::Config properties for your own purposes in cookbooks is something which should be avoided by cookbook developers, but I've seen it used in a number of places, and this appears to only be an issue in Test Kitchen due to the way it ignores the standard config file in favor of its own.)

A more ideal approach than doing `|| ENV['TEST_KITCHEN']` would be to compare the current config parameters to the ones in the file, and if there is a difference, reload from the file - but that has problems of its own.

**Comment by dheerajd-msys** [comment]
It seems this is fixed via https://github.com/chef-cookbooks/chef-client/pull/687
