### ISSUE TITLE
Running Chef Client on AIX as service creates multiple client instances

### ISSUE THREAD

**Issue by sean-horn** [chef-cookbooks/chef-client#713]
Software used
------------------

OS: AIX
Chef Infra Client: 14.4.39. Working
Chef Infra Client: 15.6.10. Failing
github.com/chef-cookbooks/chef-client: 11.2.0

Summary
--------------

* When Chef Infra Client 14.4.39 is used to run chef-client cookbook version 11.2.0 service recipe, things seem to work. the chef-client service process gets setup

* When Chef Infra Client 15.6.10 is used to run chef-client cookbook version 11.2.0, we get the following `Actual Behavior`, which is undesirable

Expected Behavior
--------------------------

Service setup by chef-client cookbook default recipe runs a daemonized chef-client which spawns a single child to handle chef-client runs on its defined interval.

Actual Behavior
-------------------

When running under Chef Infra Client 15.6.10, an extra client instance is started without the ` chef-client -d` option from the startsrc process under ksh. Then, it seems chef-client child processes get spawned, orphaned, and later reparented under PID 1.

`/bin/ksh /usr/bin/chef-client -i 1800 -s 300` (Newly appearing process when using chef client 15.6.10 which starts and stops when the startsrc service definition is started/stopped)

`/opt/chef/embedded/bin/ruby --disable-gems /opt/chef/bin/chef-client-bin -i 1800 -s 300` (Same process on old and new client versions which starts with the service but is not stopped with the service when using Chef Infra Client 15.6.10)

The additional client starts and reparentings are leading to lots of garbage in the logs 

Additional Info
---------------------

Here is an output of several starts of the chef-client under the service manager startsc

```
# /usr/bin/startsrc -s chef
0513-059 The chef Subsystem has been started. Subsystem PID is 21954684.

# ps -aef |grep chef
root 17629222 21954684 61 12:57:27 - 0:00 /opt/chef/embedded/bin/ruby --disable-gems /opt/chef/bin/chef-client-bin -i 1800 -s 300
root 18415656 1 0 12:57:06 - 0:03 /opt/chef/embedded/bin/ruby --disable-gems /opt/chef/bin/chef-client-bin -i 1800 -s 300
root 21954684 15401166 0 12:57:27 - 0:00 /bin/ksh /usr/bin/chef-client -i 1800 -s 300

# /usr/bin/stopsrc -s chef
0513-044 The chef Subsystem was requested to stop.

# /usr/bin/startsrc -s chef
0513-059 The chef Subsystem has been started. Subsystem PID is 16187590.

# ps -aef |grep chef
root 16187590 15401166 0 12:57:43 - 0:00 /bin/ksh /usr/bin/chef-client -i 1800 -s 300
root 17629222 1 0 12:57:27 - 0:03 /opt/chef/embedded/bin/ruby --disable-gems /opt/chef/bin/chef-client-bin -i 1800 -s 300
root 17694924 16187590 112 12:57:43 - 0:00 /opt/chef/embedded/bin/ruby --disable-gems /opt/chef/bin/chef-client-bin -i 1800 -s 300
root 18415656 1 0 12:57:06 - 0:03 /opt/chef/embedded/bin/ruby --disable-gems /opt/chef/bin/chef-client-bin -i 1800 -s 300
```
```

**Comment by tas50** [comment]
This should be fixed in 12.3.3
